---
sidebar: sidebar 
permalink: workflows_infra/wf_enable_anf_dyn_pools.html 
keywords: Azure NetApp Files, ANF, dynamic ANF pools, subscription id 
summary: Wenn Sie eine gemanagte App in einem privaten On-Premises-Cluster mit einem ANF-Storage-Back-End sichern, müssen Sie die Funktion Dynamic ANF Pools aktivieren. Dazu wird eine Abonnement-ID zur Verfügung gestellt, die beim erweitern und Verkleinern der Kapazitäts-Pools verwendet wird. 
---
= Aktivieren Sie dynamische ANF-Pools für selbst gemanagte Cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie eine gemanagte App in einem privaten On-Premises-Cluster mit einem ANF-Storage-Back-End sichern, müssen Sie die Funktion Dynamic ANF Pools aktivieren. Dazu wird eine Abonnement-ID zur Verfügung gestellt, die beim erweitern und Verkleinern der Kapazitäts-Pools verwendet wird.


NOTE: Dynamic ANF Pools ist eine Funktion der von Astra gemanagten Applikationen, die ein Azure NetApp Files (ANF) Storage-Back-End verwenden. Beim Backup dieser Applikationen erweitert und schließt Astra automatisch die Kapazitätspools, zu denen die persistenten Volumes gehören, um den Faktor 1.5. Dadurch wird sichergestellt, dass genügend Speicherplatz für das Backup zur Verfügung steht, ohne dass eine zusätzliche permanente Gebühr entsteht. Siehe https://docs.netapp.com/us-en/astra-control-service/learn/azure-storage.html#application-backups["Backups von Azure-Applikationen"^] Finden Sie weitere Informationen.



=== 1. Fügen Sie die Azure-Abonnement-ID hinzu

Führen Sie den folgenden REST-API-Aufruf aus.


NOTE: Sie müssen das JSON-Eingabebeispiel entsprechend Ihrer Umgebung aktualisieren, einschließlich der Abonnement-ID und dem base64-Wert für den Service-Prinzipal.

[cols="1,6"]
|===
| HTTP-Methode | Pfad 


| POST | /Accounts/{Account_id}/Core/v1/Credentials 
|===
.JSON-Eingabebeispiel
[source, json]
----
{
  "keyStore": {
    "privKey": "SGkh",
    "pubKey": "UGhpcyCpcyBhbiBleGFtcGxlLg==",
    "base64": "fwogICAgJmFwcElkIjogIjY4ZmSiODFiLTY0YWYtNDdjNC04ZjUzLWE2NDdlZTUzMGZkZCIsCiAgICAiZGlzcGxheU5hbWUiOiAic3AtYXN0cmEtZGV2LXFhIiwKICAgICJuYW1lIjogImh0dHA6Ly9zcC1hc3RyYS1kZXYtcWEiLAogICAgInBhc3N3b3JkIjogIllLQThRfk9IVVJkZWZYM0pSTWJlLnpUeFBleVE0UnNwTG9DcUJjazAiLAogICAgInRlbmFudCI6ICIwMTFjZGY2Yy03NTEyLTQ3MDUtYjI0ZS03NzIxYWZkOGNhMzciLAogICAgInN1YnNjcmlwdGlvbklkIjogImIyMDAxNTVmLTAwMWEtNDNiZS04N2JlLTNlZGRlODNhY2VmNCIKfQ=="
  },
  "name": "myCert",
  "type": "application/astra-credential",
  "version": "1.1",
  "metadata": {
    "labels": [
      {
        "name": "astra.netapp.io/labels/read-only/credType",
        "value": "service-account"
      },
      {
        "name": "astra.netapp.io/labels/read-only/cloudName",
        "value": "OCP"
      },
      {
        "name": "astra.netapp.io/labels/read-only/azure/subscriptionID",
        "value": "b212156f-001a-43be-87be-3edde83acef5"
      }
    ]
  }
}
----
.Beispiel für die Wellung
[source, curl]
----
curl --location -i --request POST --data @JSONinput 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/credentials' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --header 'Content-Type: application/astra-credential+json'
----


=== 2. Fügen Sie bei Bedarf einen Eimer hinzu

Sie sollten bei Bedarf der verwalteten Anwendung einen Bucket hinzufügen.



=== 3. Nehmen Sie ein Backup der verwalteten App

Führen Sie den Workflow aus link:../workflows/wf_create_backup.html["Backup für eine Anwendung erstellen"]. Der Kapazitäts-Pool, in dem das ursprüngliche persistente Volume vorhanden ist, wird automatisch erweitert oder verkleinert.



=== 4. Überprüfen Sie das Ereignisprotokoll

Aktivitätsereignisse werden während des Backups protokolliert. Führen Sie den Workflow aus link:../workflows/wf_list_notifications.html["Listen Sie die Benachrichtigungen auf"] Um die Nachrichten anzuzeigen.
