---
sidebar: sidebar 
permalink: workflows_infra/wf_list_users.html 
keywords:  
summary: Sie können die Benutzer auflisten, die für ein bestimmtes Astra-Konto definiert sind. 
---
= Listen Sie die Benutzer auf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Benutzer auflisten, die für ein bestimmtes Astra-Konto definiert sind.



=== 1. Listen Sie die Benutzer auf

Führen Sie den folgenden REST-API-Aufruf aus.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /Accounts/{Account_id}/Core/v1/users 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| Einschließlich | Abfrage | Nein | Wählen Sie optional die Werte aus, die in der Antwort zurückgegeben werden sollen. 
|===


===== Curl-Beispiel: Alle Daten für alle Benutzer zurückgeben

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/users' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl Beispiel: Gibt den vor-, Nachnamen und die id für alle Benutzer zurück

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/users?include=firstName,lastName,id' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Beispiel für eine JSON-Ausgabe

[source, curl]
----
{
  "items": [
    [
    "David",
    "Anderson",
    "844ec6234-11e0-49ea-8434-a992a6270ec1"
    ],
    [
      "Jane",
      "Cohen",
      "2a3e227c-fda7-4145-a86c-ed9aa0183a6c"
    ]
  ],
  "metadata": {}
}
----