---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-settings.html 
summary: Alle Einstellungen auflisten 
---
= Alle Einstellungen auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/settings`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"



| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"



| Zählen | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, ob die Gesamtzahl der Ressourcen im Metadatenobjekt zurückgegeben werden soll.

URL-Beispiele: "count=true"

OpenAPI-Beispiele: "true"



| Orderby | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Sortierreihenfolge der Ressourcen beim Auflisten einer Sammlung an.

URL-Beispiele: "orderBy=name", "orderBy=name%20desc"

OpenAPI-Beispiele: "name desc"



| überspringen | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Anzahl der Ressourcen an, die beim Auflisten einer Sammlung übersprungen werden sollen.

URL-Beispiele: "skip=1"

OpenAPI-Beispiele: "1"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#setting_1_1_get_response_body["setting_1.1_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-settings",
  "version": "1.1",
  "items": [
    {
      "type": "application/astra-setting",
      "version": "1.0",
      "id": "5da0a2ed-c51d-4d91-8b98-ed3aa8a88cc5",
      "name": "astra.account.smtp",
      "currentConfig": {
        "credential": "",
        "isEnabled": "false",
        "port": 587,
        "relayServer": "smtp.sendgrid.net"
      },
      "configSchema": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "astra.account.smtp",
        "type": "object",
        "properties": {
          "credential": {
            "type": "string",
            "description": "The credential ID for SMTP authentication."
          },
          "isEnabled": {
            "type": "string",
            "description": "This property determines if this setting is enabled or not."
          },
          "port": {
            "type": "integer",
            "description": "The SMTP port. For an unencrypted or a TLS connection, use port 25, 2525, or 587."
          },
          "relayServer": {
            "type": "string",
            "description": "This setting is sometimes referred to as the external SMTP server or the SMTP relay."
          }
        },
        "additionalProperties": false,
        "required": [
          "relayServer",
          "port",
          "isEnabled"
        ]
      },
      "state": "valid",
      "stateUnready": [],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2021-06-04T20:14:52Z",
        "modificationTimestamp": "2021-06-04T20:14:52Z",
        "createdBy": "c9550bbb-e70b-4578-8504-07397f875bcb",
        "modifiedBy": "65e1571b-1b46-4f05-95b0-7d7f5a93da6a"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Antwort

[source]
----
Status: 503, Service unavailable
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/41",
  "title": "Service not ready",
  "detail": "Currently, the service can't respond to this request.",
  "status": "503"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_json

Ein JSON-Objekt mit Schlüsseln und Werten, die die aktuelle Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema-Feld enthaltenen JSON-Schema entsprechen. Standardwerte werden von der configmap bereitgestellt. Nachdem die Standardwerte vom Benutzer geändert wurden, werden sie nicht überschrieben.

[role="api-collapsible-fifth-title"]
type_json

Ein JSON-Objekt mit Schlüsseln und Werten, die die angeforderte Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema-Feld enthaltenen JSON-Schema entsprechen. Das Objekt existiert erst, wenn es angegeben wurde. Wenn angegeben, veranlasst dies den Feature-Service, den entsprechenden Service zu benachrichtigen, damit die gewünschte Konfiguration angefordert werden kann. Der entsprechende Service kann dann die Validierung durchführen und die gewünschte Konfiguration auf die aktuelle Konfiguration anwenden.

[role="api-collapsible-fifth-title"]
Eigenschaften

[role="api-collapsible-fifth-title"]
type_json_schema

JSON-Objekt, das das JSON-Schema für die config-Eigenschaft in dieser Ressource enthält. Muss JSON Schema Draft 7 entsprechen. Wenn config-Werte in der Ressource vorhanden sind, ist die Validierung gegen das angegebene configSchema obligatorisch. Als allgemeine Konvention wird empfohlen, dass Konfigurationen ein "isEnabled"-Feld haben, wenn angemessen. Das "isEnabled"-Feld enthält einen Wert, der angibt, ob die Einstellung eingeschaltet ("true") oder ausgeschaltet ("false") ist.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| $schema | Zeichenkette | Wahr  a| 



| Typ | Zeichenkette | Wahr  a| 



| Eigenschaften | link:#properties["Eigenschaften"] | Wahr  a| 



| additionalProperties | boolescher Wert | Wahr  a| 



| erforderlich | Array[string] | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Falls beim Aktualisieren nichts anderes angegeben wird, werden die Bezeichnungen, creationTimestamp und createdBy des Metadatenobjekts unverändert beibehalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
setting_1.1_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-setting"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Namen für die Einstellung in hierarchischer Punktnotation (.). Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63
* Diese Zeichenkette wird intern validiert, um XSS-, Unicode-, Directory-Traversal- und SQL-Injection-Angriffe zu verhindern. Dieser Wert wird durch die zur Laufzeit geladene configmap festgelegt und kann vom Benutzer nicht geändert werden.




| currentConfig | link:#type_json["type_json"] | Wahr  a| 
Ein JSON-Objekt mit Schlüsseln und Werten, die die aktuelle Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema-Feld enthaltenen JSON-Schema entsprechen. Standardwerte werden von der configmap bereitgestellt. Nachdem die Standardwerte vom Benutzer geändert wurden, werden sie nicht überschrieben.



| desiredConfig | link:#type_json["type_json"] | Falsch  a| 
Ein JSON-Objekt mit Schlüsseln und Werten, die die angeforderte Konfiguration für diese Einstellung bilden. Der Inhalt dieses Objekts muss dem im configSchema-Feld enthaltenen JSON-Schema entsprechen. Das Objekt existiert erst, wenn es angegeben wurde. Wenn angegeben, veranlasst dies den Feature-Service, den entsprechenden Service zu benachrichtigen, damit die gewünschte Konfiguration angefordert werden kann. Der entsprechende Service kann dann die Validierung durchführen und die gewünschte Konfiguration auf die aktuelle Konfiguration anwenden.



| configSchema | link:#type_json_schema["type_json_schema"] | Wahr  a| 
JSON-Objekt, das das JSON-Schema für die config-Eigenschaft in dieser Ressource enthält. Muss JSON Schema Draft 7 entsprechen. Wenn config-Werte in der Ressource vorhanden sind, ist die Validierung gegen das angegebene configSchema obligatorisch. Als allgemeine Konvention wird empfohlen, dass Konfigurationen ein "isEnabled"-Feld haben, wenn angemessen. Das "isEnabled"-Feld enthält einen Wert, der angibt, ob die Einstellung eingeschaltet ("true") oder ausgeschaltet ("false") ist.



| Zustand | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand der Anwendung angibt. Folgende Werte sind definiert:

* "gültig" - Die aktuelle Konfiguration entspricht der gewünschten Konfiguration.
* "Ausstehend" - Die gewünschte Konfiguration wird angewendet.
* "Fehler" - Die gewünschte Konfiguration kann nicht angewendet werden.




| stateUnready | Array[string] | Wahr  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum die Einstellung nicht erfolgreich angewendet wurde. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Falls beim Aktualisieren nichts anderes angegeben wird, werden die Bezeichnungen, creationTimestamp und createdBy des Metadatenobjekts unverändert beibehalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====