---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-storagebackends.html 
summary: Alle Speicher-Backends auflisten 
---
= Alle Speicher-Backends auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/storageBackends`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: id,name,state




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#storageBackend_1_3_get_response_body["storageBackend_1.3_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageBackends",
  "version": "1.3",
  "items": [
    [
      "d6ee1e51-d65f-415a-a3d4-6d7fa8b64943",
      "st1-45",
      "running"
    ],
    [
      "a5c508b7-aacd-4d19-9455-53c0d183ab4e",
      "st2-67",
      "discovered"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Fähigkeiten

JSON-Objekt, das die Funktionen dieses Storage Backend enthält.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| FlexClone | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob dieses Storage Backend FlexClone unterstützt.



| SnapMirror | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob dieses Storage Backend SnapMirror unterstützt.



| s3 | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob dieses Storage Backend S3 unterstützt.

|===
[role="api-collapsible-fifth-title"]
ONTAP

JSON-Objekt mit spezifischen Informationen zu ONTAP Clustern.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| authenticationStyle | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob die ONTAP Authentifizierung mittels Benutzername/Passwort-Kombination oder Zertifikat erfolgt. Folgende Werte sind definiert:

* "basic" - Verwendet Benutzername/Passwort
* "Zertifikat" - Verwendet Zertifikat
* enum: ["basic", "certificate"]
* Beispiel: grundlegend




| backendManagementIP | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die die IP-Adresse enthält, die zur Verbindung mit diesem ONTAP Cluster verwendet wird.



| Management-IPs | Array[string] | Falsch  a| 
Ein JSON-Array mit JSON-Strings, das die Liste aller möglichen Management-IPs enthält, die zur Verbindung mit diesem ONTAP Cluster verwendet werden. Dies wird verwendet, um Backends, die über Trident erkannt wurden, mit Speicher-Backends in Astra zu korrelieren.

* uniqueItems: 1


|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
storageBackend_1.3_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-storageBackend"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| backendName | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für das Storage-Backend. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| backendType | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Typ des dargestellten Speichersystems angibt. Folgende Werte sind definiert:

* "ontap" – Das Speicher-Backend stellt ein NetApp ONTAP System dar.
* enum: ["ontap"]
* Beispiel: ONTAP




| backendVersion | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der die Version des verwendeten Storage-Backends angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| backendCredentialsName | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit einem Wert, der den Namen einer oder mehrerer für das Speicher-Backend verwendeter Anmeldeinformationsressourcen angibt. Ermöglicht die Rotation von Anmeldeinformationen, wenn mehrere Anmeldeinformationsobjekte denselben Namen haben. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| configVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die vom Speichersystem zu verwendende aktive Konfiguration angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| Zustand | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand des Storage-Backends angibt. Definierte Werte sind:

* „Erkannt“ – Das Speicher-Backend wurde von einem verwalteten Cluster erkannt.
* "läuft" – Das Storage-Backend läuft normal
* "unbekannt" – Der Status des Storage-Backends kann nicht ermittelt werden
* „failed“ – Das Storage-Backend befindet sich in einem nicht verfügbaren Zustand




| stateDesired | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den gewünschten Betriebszustand des Storage-Backends angibt. Definierte Werte sind:

* "läuft" - Das Storage-Backend befindet sich im normalen Betriebszustand




| stateUnready | Array[string] | Wahr  a| 
JSON-Array von JSON-Strings, die jeweils einen Grund dafür angeben, warum ein Storage-Backend nicht in den Status „running“ wechseln kann, warum es in den Status „failed“ oder „unknown“ gewechselt ist und/oder warum ein Wechsel in den Status „failed“ droht. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| managedState | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Verwaltungsstatus des Storage-Backends angibt. Definierte Werte sind:

* „pending“ – Das Storage-Backend ist zur Erkennung oder Hinzufügung geplant
* „unmanaged“ – Das Storage-Backend befindet sich im Status „discovered“, wird nicht verwaltet und ist für die Verwaltung geeignet
* „managed“ – Das Storage-Backend befindet sich im Status „running“ oder „unknown“ und wird verwaltet.




| managedStateUnready | Array[string] | Wahr  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum das Storage-Backend nicht verwaltet werden kann. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| healthState | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Integritätsstatus des Speichersystems angibt. Folgende Werte sind definiert:

* „unbestimmt“ – Der Zustand der Ressource kann nicht bestimmt werden (z. B. aufgrund fehlender Verbindung)
* „normal“ – Die Ressource weist keine bekannten Probleme auf und kann Dienste gemäß der Schnittstellenspezifikation bereitstellen.
* "Warnung" – Die Ressource weist bekannte Probleme auf, die sie jedoch nicht daran hindern, Dienste gemäß der Schnittstellenspezifikation bereitzustellen.
* "kritisch" – Die Ressource weist bekannte Probleme auf, die sie daran hindern, Dienste gemäß der Schnittstellenspezifikation bereitzustellen.




| healthStateUnready | Array[string] | Falsch  a| 
JSON-Array von JSON-Strings, die jeweils einen Grund dafür angeben, warum sich ein Storage-Backend nicht in einem normalen Gesundheitszustand befindet. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| protectionState | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Schutzstatus des Storage-Backends angibt. „unknown“ für ONTAP. Definierte Werte sind:

* „geschützt“ – Das Storage-Backend verfügt über eine Datensicherungsstrategie und entspricht dieser Strategie.
* „teilweise“ – Das Storage-Backend hat eine Datensicherungsstrategie definiert, entspricht dieser jedoch nicht.
* „none“ – Das Storage-Backend ist nicht geschützt
* "unbekannt" – Die Einhaltung der Datensicherungsstrategie des Storage-Backends kann nicht ermittelt werden
* enum: ["geschützt", "teilweise", "keine", "unbekannt"]
* Beispiel: geschützt




| protectionStateUnready | Array[string] | Wahr  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum eine Datensicherungsstrategie nicht den Vorgaben entspricht. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| Fähigkeiten | link:#capabilities["Fähigkeiten"] | Wahr  a| 
JSON-Objekt, das die Funktionen dieses Storage Backend enthält.



| ONTAP | link:#ontap["ONTAP"] | Falsch  a| 
JSON-Objekt mit spezifischen Informationen zu ONTAP Clustern.

* additionalProperties: false




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====