---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-executionhookoverrides.html 
summary: Listen Sie die Ressourcen zum Überschreiben des Ausführungs-Hooks für eine App auf 
---
= Listen Sie die Ressourcen zum Überschreiben des Ausführungs-Hooks für eine App auf
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHookOverrides`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.


CAUTION: Diese Funktion ist veraltet.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| App-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten App-Ressource



| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"



| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#executionHookOverride_1_0_get_response_body["executionHookOverride_1.0_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverrides",
  "version": "1.0",
  "items": [
    {
      "type": "application/astra-executionHookOverride",
      "version": "1.0",
      "id": "36d06222-bd0c-4897-89c2-c16dd9265e12",
      "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
      "enabled": "false",
      "appID": "4b43c2f7-bffa-4f60-b595-d98a05b64bc9",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "863feb92-8619-4298-b222-c48a886024f8"
      }
    },
    {
      "type": "application/astra-executionHookOverride",
      "version": "1.0",
      "id": "f8d1ce66-6c0e-4d3a-96c5-a5e76669442d",
      "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
      "enabled": "false",
      "appID": "36b076ae-b7c4-4e96-a323-ed167ede74ba",
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "863feb92-8619-4298-b222-c48a886024f8"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
executionHookOverride_1.0_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-executionHookOverride"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| executionHookID | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der ID eines Ausführungs-Hooks. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema. Erlaubt ausschließlich die executionHookID einer Ausführungshook-Ressource mit einem hookType-Wert von "netapp".




| aktiviert | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob der Ausführungshook für die angegebene Anwendung aktiviert ist. Folgende Werte sind definiert:

* "true" - Der Ausführungs-Hook ist aktiviert und wird in der angegebenen Reihenfolge ausgeführt
* "false" - Der Ausführungshook ist deaktiviert und kann nicht ausgeführt werden




| App-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit der zugehörigen ID der Anwendung, mit der die Überschreibung verknüpft ist. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====