---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-licenses.html 
summary: Alle Lizenzen auflisten 
---
= Alle Lizenzen auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/licenses`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: id,Produkt




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#license_1_0_get_response_body["license_1.0_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-licenses",
  "version": "1.0",
  "items": [
    [
      "c8aa757a-5318-489f-8134-a2a1a6956a3e",
      "Astra SDS"
    ],
    [
      "0f7cc03d-9afc-4192-af7f-b29ab24f8f2a",
      "Astra Enterprise"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Add-ons

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| startDate | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann dieses Add-on gültig wird. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| endDate | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann dieses Add-on nicht mehr gültig ist. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Merkmale | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Liste der Funktionen, die diesem Add-on zugeordnet sind. Folgende Werte sind definiert:

* Der Zeichenketteninhalt wurde vom Schema nicht validiert.




| Kapazität | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus dem Add-on extrahierten Kapazität. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| licenseProtocol | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem Lizenzprotokoll dieses Add-ons. Folgende Werte sind definiert:

* Zeichenketteninhalte wurden vom Schema nicht validiert


|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
license_1.0_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-license"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Zuweisung | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit einer ID, die angibt, wem die Lizenz zugeordnet ist. Nur vorhanden, wenn die Lizenz zugeordnet ist. Bei Astra Control Center-Lizenzen muss dieses Feld die Konto-ID enthalten und mit der in der POST-URI angegebenen Konto-ID übereinstimmen. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Host-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer Host-Kennung, an die eine Lizenz gebunden ist. Nur vorhanden, wenn die Lizenz host-locked ist. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| Geräte-Anmeldeinformationen-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der Kennung der deviceCredential, die mit der Credential API verknüpft ist. Nur für Astra Data Store-Lizenzen vorhanden. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| isEvaluation | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob es sich um eine Evaluierungslizenz handelt. Folgende Werte sind definiert:

* "true"
* "false"




| licenseProtocol | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem aus der Lizenz extrahierten Lizenzprotokoll. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| licenseText | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einer Base64-kodierten Darstellung der Lizenz-JSON-Datei, wie sie vom NetApp Lizenzsystem abgerufen wurde. Diese muss in der ursprünglichen Byte-Reihenfolge angegeben werden, um die Signaturprüfung zu ermöglichen. Folgende Werte sind definiert:

* Entspricht dem Base64-kodierten Datenschema




| validFromTimestamp | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Lizenz gültig wird. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| validUntilTimestamp | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Lizenz nicht mehr gültig ist. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Produkt | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Produktzeichenkette. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| productVersion | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Versionszeichenkette. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| Produkt-SN | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Seriennummer. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| Merkmale | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem aus der Lizenz extrahierten Paketwert. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| Kapazität | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Kapazität.



| capacity2 | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die die aus der Lizenz extrahierte Sekundärkapazität enthält.



| Add-ons | Array[link:#addons["Add-ons"]] | Falsch  a| 
JSON-Array von JSON-Objekten, das die Liste der Add-ons aus der Lizenz enthält. Ein Add-on ist eine Lizenzänderung, die zu einem möglichen zukünftigen Zeitpunkt in Kraft tritt.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====