---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-schedules-.html 
summary: Einen Zeitplan abrufen 
---
= Einen Zeitplan abrufen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/schedules/{schedule_id}`#

Gibt die gespeicherte Schedule-API-Ressource im JSON-Antworttext zurück.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| App-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten App-Ressource



| Zeitplan-ID | Zeichenkette | Pfad | Wahr  a| 
ID der aufzulistenden Zeitplansammlung

|===


== Antwort

[source]
----
Status: 200, Returns the stored Schedule API resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-schedule"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem Namen des Zeitplans. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| aktiviert | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob ein Zeitplan aktiv ist. Definierte Werte sind:

* "true" - Der Zeitplan ist aktiv
* "false" – Der Zeitplan ist nicht aktiv. Wenn kein Wert angegeben ist, ist der Standardwert "true".




| Granularität | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die die Granularität des Zeitplans angibt. Definierte Werte sind:

* "stündlich"
* "täglich"
* "wöchentlich"
* "monatlich"
* "custom"




| Minute | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem numerischen Wert, der die Minute der Stunde (0–59) angibt, zu der der Zeitplan ausgeführt werden soll. Definierte Werte sind:

* Der definierte reguläre Ausdruck lautet: "^[0-9]|[1-5][0-9]$". Dieses Feld ist vorhanden, wenn die Granularität auf "stündlich", "täglich", "wöchentlich" oder "monatlich" gesetzt ist. Es wird mit dem Wert "0" für benutzerdefinierte Zeitpläne zurückgegeben.




| Stunde | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem numerischen Wert, der die Stunde des Tages (0–23) angibt, zu der der Zeitplan ausgeführt werden soll. Definierte Werte sind:

* Der definierte reguläre Ausdruck lautet: "^[0-9]|[1][0-9]|[2][0-3]$" Dieses Feld ist vorhanden, wenn Granularität auf "täglich", "wöchentlich" oder "monatlich" eingestellt ist.




| dayOfWeek | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem numerischen Wert, der den Wochentag (0-7) für die Ausführung des Zeitplans angibt. Folgende Werte sind definiert:

* Der definierte reguläre Ausdruck lautet: "^[0-7]$" Dieses Feld ist nur vorhanden, wenn Granularität auf "wöchentlich" eingestellt ist.




| dayOfMonth | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem numerischen Wert, der den Tag des Monats (1-31) angibt, an dem der Zeitplan ausgeführt werden soll. Definierte Werte sind:

* Der definierte reguläre Ausdruck lautet: "^[1-9]|[1-2][0-9]|[3][0-1]$" Dieses Feld ist nur vorhanden, wenn Granularität auf "monthly" eingestellt ist.




| recurrenceRule | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer RFC-5545 Abschnitt 3.8.5.3. Wiederholungsregel. Für den Parameter DTSTART werden ausschließlich UTC-Zeitstempel (gekennzeichnet durch das Suffix „Z“) unterstützt, und es werden nur Zeitstempel vor der aktuellen Zeit unterstützt. Für die RECUR-Regelbestandteile werden nur „FREQ“ und „INTERVAL“ unterstützt. Für den FREQ-Regelbestandteil werden nur die Werte „MINUTELY“ und „HOURLY“ unterstützt. Dieses Feld ist nur vorhanden, wenn Granularität auf „custom“ gesetzt ist.



| snapshotRetention | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem positiven numerischen Wert, der angibt, wie viele Snapshots aufbewahrt werden sollen. Null bedeutet, dass Snapshots nach der Sicherung gelöscht werden sollen. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63
* Der definierte reguläre Ausdruck lautet: "^(0|([1-9][0-9]*))$"




| backupRetention | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem positiven numerischen Wert, der angibt, wie viele Backups aufbewahrt werden sollen. Null bedeutet, dass keine Backups erstellt werden sollen. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63
* Der definierte reguläre Ausdruck lautet: "^(0|([1-9][0-9]*))$"




| bucketID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit einer optionalen Bucket-ID, die angibt, wo das Backup beim Erstellen gespeichert werden soll. Wird keine Bucket-ID angegeben, wird ein vom System ausgewählter Bucket verwendet. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| replizieren | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, ob der Zeitplan die AppMirror-Replikation für jeden Snapshot auslöst. Wirkt sich nur aus, wenn für die Anwendung eine AppMirror-Beziehung definiert ist. Definierte Werte sind:

* "true" – Der Zeitplan löst AppMirror Replikation aus
* "false" – Der Zeitplan löst keine AppMirror Replikation aus. Wenn kein Wert angegeben ist, ist der Standardwert "false".




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "id": "49cbc480-5f7d-51e2-8f30-52b9a83a03b1",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====