---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-events.html 
summary: Alle Ereignisse auflisten 
---
= Alle Ereignisse auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/events`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: id,summary




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"



| Orderby | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Sortierreihenfolge der Ressourcen beim Auflisten einer Sammlung an.

URL-Beispiele: "orderBy=name", "orderBy=name%20desc"

OpenAPI-Beispiele: "name desc"



| überspringen | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Anzahl der Ressourcen an, die beim Auflisten einer Sammlung übersprungen werden sollen.

URL-Beispiele: "skip=1"

OpenAPI-Beispiele: "1"



| Zählen | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, ob die Gesamtzahl der Ressourcen im Metadatenobjekt zurückgegeben werden soll.

URL-Beispiele: "count=true"

OpenAPI-Beispiele: "true"



| fortfahren |  | Abfrage | Falsch  a| 
Gibt das Token an, von dem aus die Auflistung fortgesetzt werden soll.

URL-Beispiele: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPI-Beispiele: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#event_1_4_get_response_body["event_1.4_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-events",
  "version": "1.4",
  "items": [
    [
      "4f8273ee-883d-47f0-a512-9e27b6285f20",
      "Discovering Applications in Cluster"
    ],
    [
      "1cdd26dc-5eb0-4cf4-a0c1-39a9b83720e1",
      "Application Discovered"
    ],
    [
      "2064d1c1-4bc6-466e-9c30-b941a11be16a",
      "Application Discovery Failed"
    ],
    [
      "4325f971-ca9c-4a52-bc9a-da6ec62e6bfe",
      "Application Discovered"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Daten

JSON-Objekt mit zusätzlichen ereignisspezifischen Informationen.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| ttl | Nummer | Falsch  a| 
JSON-Zahl, die die Anzahl der Sekunden (seit dem eventTime), die das Ereignis aufbewahrt wird, angibt. Dieses Feld ist nur enthalten, wenn ein Ereignis nach der angegebenen Anzahl von Sekunden automatisch gelöscht wird. Beim Löschen werden, falls das Ereignis ein Benachrichtigungsziel hat, auch alle zugehörigen Benachrichtigungen gelöscht. Beim Löschen wird, falls das Ereignis ein Bannerziel hat, auch das Banner entfernt. Das Fehlen dieses Feldes (oder ein Wert von „0“) bedeutet, dass ein Ereignis nicht automatisch gelöscht wird.



| isAcknowledgeable | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, ob das Banner ausgeblendet werden kann. Folgende Werte sind definiert:

* "true" – Das Banner kann ausgeblendet werden.
* "falsch" - Das Banner ist nicht ausblendbar


|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra Metadatenschema


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Wahr  a| 



| CreationZeitstempel | Zeichenkette | Wahr  a| 



| Änderungszeitstempel | Zeichenkette | Wahr  a| 



| Erstellt von | Zeichenkette | Wahr  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
event_1.4_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-event"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"
* "1,3"
* "1,4"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem hierarchischen Namen für das Ereignis, der durch Punktnotation (.) dargestellt wird. Definierte Werte sind:

* Mindestlänge: 3
* Maximale Länge: 127
* Definierter regulärer Ausdruck ist: „^(([a-z])_(\.))_([a-z])+$“




| sequenceCount | Nummer | Wahr  a| 
Eine JSON-Zahl, die einen Sequenzzähler enthält. Die Zahl wird vom System jedes Mal erhöht, wenn ein neues Ereignis empfangen wird.



| Zusammenfassung | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der Kurzfassung (weniger als 40 Zeichen) des Ereignisses. Folgende Werte sind definiert:

* Mindestlänge: 3
* Maximale Länge: 79




| eventTime | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann ein Ereignis stattgefunden hat. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Quelle | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem in Kleinbuchstaben geschriebenen Namen des Dienstes, der ein Ereignis generiert. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 19
* Der definierte reguläre Ausdruck lautet: "^([a-z-])*$"




| Ressourcen-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der Ressourcen-ID eines Ereignisses. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| zusätzliche Ressourcen-IDs | Array[string] | Wahr  a| 
JSON-Array von JSON-Strings, die jeweils eine Ressourcen-ID einer zusätzlichen, dem Ereignis zugeordneten Ressource enthalten. Während das Feld „resourceID“ die primäre Ressource dieses Ereignisses enthält, enthält dieses Feld beliebig viele zusätzliche Ressourcen-IDs, die demselben Ereignis zugeordnet werden. Wenn keine zusätzlichen Ressourcen mit dem Ereignis verknüpft sind, ist das Array leer. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| resourceType | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die den Medientyp der einem Ereignis zugeordneten Ressource enthält. Definierte Werte sind:

* Mindestlänge: 4
* Maximale Länge: 79
* Der definierte reguläre Ausdruck lautet: "^application\/astra-([a-zA-Z])+$"




| Korrelations-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einer UUIDv4-Korrelations-ID, die das Gruppieren zusammengehöriger Ereignisse ermöglicht. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| severity | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem der folgenden Werte, die den Schweregrad eines Ereignisses angeben. Definierte Werte sind:

* „cleared“ – Dies bedeutet, dass ein zuvor gemeldetes Ereignis, das einen Zustand beschreibt, nicht mehr aktiv ist. Ein Ereignis mit Schweregrad „cleared“ verwendet dieselbe Zusammenfassungs- und Korrelations-ID, um die Zuordnung zu ermöglichen.
* „unbestimmt“ – Gibt an, dass der Schweregrad nicht bestimmt werden kann.
* „informational“ – Bezeichnet eine Zustandsänderung, die sowohl erwartet als auch normal ist (nicht definiert in X.733).
* „Warnung“ – Zeigt die Erkennung eines potenziellen oder bevorstehenden, den Service beeinträchtigenden Fehlers an, bevor nennenswerte Auswirkungen spürbar werden.
* „Kritisch“ bedeutet, dass ein betriebsbeeinträchtigender Zustand aufgetreten ist und sofortige Korrekturmaßnahme erforderlich ist. Die Definitionen für „behoben“, „unbestimmt“, „Warnung“ und „kritisch“ basieren auf den Definitionen in Abschnitt 8.1.2.3 von CCITT X.733.




| Klasse | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem der folgenden Werte, die die Klasse des Ereignisses angeben. Definierte Werte sind:

* „system“ – Das Ereignis steht im Zusammenhang mit einem internen Ereignis oder einer internen Anfrage.
* „Benutzer“ – Das Ereignis bezieht sich auf ein vom Benutzer initiiertes Ereignis oder eine Anfrage.
* „Sicherheit“ – Das Ereignis steht im Zusammenhang mit einem Sicherheitsproblem.




| description | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem ausführlichen beschreibenden Text zum Ereignis. Definierte Werte sind:

* Mindestlänge: 3
* Maximale Länge: 1023




| descriptionURL | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der URL, die eine Schaltfläche im Banner aktiviert und mit einer externen Dokumentation verlinkt. Definierte Werte sind:

* Mindestlänge: 3
* Maximale Länge: 4095




| correctiveAction | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem ausführlichen beschreibenden Text darüber, welche Korrekturmaßnahme als Reaktion auf das Ereignis ergriffen werden muss. Folgende Werte sind definiert:

* Mindestlänge: 3
* Maximale Länge: 1023




| Korrekturmaßnahme-URL | Zeichenkette | Falsch  a| 
JSON-String mit der URL, die eine Schaltfläche im Banner mit einer Seite innerhalb der Benutzeroberfläche verknüpft, um das Problem zu beheben. Definierte Werte sind:

* Mindestlänge: 3
* Maximale Länge: 4095




| Sichtbarkeit | Array[string] | Falsch  a| 
JSON-Array von JSON-Strings, die jeweils eine RBAC-Rolle angeben, die berechtigt ist, das Ereignis anzuzeigen. Rollen werden mit ODER verknüpft. Optional. Falls weggelassen, kann ein Benutzer mit jeder RBAC-Rolle das Ereignis anzeigen. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| Ziele | Array[string] | Falsch  a| 
JSON-Array von JSON-Strings, die jeweils ein zusätzliches Ziel für das Ereignis angeben. Diese Strings ermöglichen es einem Service, Hinweise darüber zu geben, wohin ein Ereignis zusätzlich zum Aktivitätsprotokoll weitergeleitet werden soll. Optional. Definierte Werte sind:

* „Benachrichtigung“ – Das Ereignis ist als Benachrichtigung gekennzeichnet und wird über den Benachrichtigungen-API-Endpunkt zugänglich sein.
* "banner" - Die Veranstaltung ist als Banner gekennzeichnet.
* „support“ – Das Ereignis ist als support-bezogenes Ereignis gekennzeichnet.




| resourceURI | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der URI des Ereignisses. Nur für Ereignisse im Zusammenhang mit API-Operationen enthalten. Definierte Werte sind:

* Mindestlänge: 3
* Maximale Länge: 4095




| resourceCollectionURL | Array[string] | Falsch  a| 
JSON-Array von JSON-Zeichenketten, die jeweils die vollständig expandierte Zugriffs-URL der mit dem Ereignis verknüpften Ressource angeben. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 1023




| resourceMethod | Zeichenkette | Falsch  a| 
JSON-String mit der aufgerufenen HTTP-Methode. Wird nur für Ereignisse im Zusammenhang mit API-Operationen bereitgestellt. Folgende Werte sind definiert:

* "options" - OPTIONS API-Operation
* "post" - POST-API-Operation
* "get" - GET-API-Operation
* "put" - PUT-API-Operation
* "delete" - DELETE-API-Operation




| resourceMethodResult | Zeichenkette | Falsch  a| 
JSON-String mit dem Ergebnis der aufgerufenen HTTP-Methode. Wird nur für Ereignisse im Zusammenhang mit API-Operationen bereitgestellt. Definierte Werte sind:

* Der definierte reguläre Ausdruck lautet: "^[1-5][0-9]{2}$"




| Benutzer-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Benutzer-ID, die mit einem Ereignis verknüpft ist. Nur für Ereignisse enthalten, die mit benutzerinitiierten Aktionen verbunden sind. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Konto-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Konto-ID, die mit einem Ereignis verknüpft ist. Nur für Ereignisse enthalten, die mit einem Konto verknüpft sind. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Daten | link:#data["Daten"] | Falsch  a| 
JSON-Objekt mit zusätzlichen ereignisspezifischen Informationen.



| Metadaten | link:#type_astra_metadata["type_astra_metadata"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra Metadatenschema


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====