---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-credentials.html 
summary: Alle Anmeldeinformationen auflisten 
---
= Alle Anmeldeinformationen auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| fortfahren |  | Abfrage | Falsch  a| 
Gibt das Token an, von dem aus die Auflistung fortgesetzt werden soll.

URL-Beispiele: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPI-Beispiele: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"



| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: id,name




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Orderby | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Sortierreihenfolge der Ressourcen beim Auflisten einer Sammlung an.

URL-Beispiele: "orderBy=name", "orderBy=name%20desc"

OpenAPI-Beispiele: "name desc"

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#credential_1_1_get_response_body["credential_1.1_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credentials",
  "version": "1.1",
  "items": [
    [
      "f97f3441-075e-4f9b-9d1e-47f9f62a3fc4",
      "myCert"
    ],
    [
      "5e365b4d-034f-4f13-95ef-d3a7fbc0df3d",
      "kubeconfig"
    ],
    [
      "11ceb350-1999-4b79-80a6-46a980a27856",
      "password"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
credential_1.1_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-credential"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit einem benutzerdefinierten Namen. Beim Erstellen von Anmeldeinformationen für einen Benutzer wird der Name auf die UUID dieses Benutzers gesetzt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 127




| keyType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem optionalen, vom Benutzer festgelegten Datenvalidierungstypdeskriptor für den Inhalt der keyStore. Erweiterte Aktualisierungseinschränkungen:

* Wenn ein keyType in der Ressource nicht existiert und in einem Update nicht angegeben wird, darf der keyType in der aktualisierten Ressource nicht mehr existieren.
* Wenn ein keyType in der Ressource nicht existiert und in einer Aktualisierung angegeben wird, muss der keyType der Ressource hinzugefügt und eine Validierung durchgeführt werden. Wenn die Validierung fehlschlägt, schlägt die Aktualisierung fehl.
* Wenn ein keyType in der Ressource existiert und in einem Update nicht angegeben wird, muss der keyType beibehalten werden.
* Wenn ein keyType in der Ressource existiert und in einem Update angegeben wird und das angegebene keyType mit dem vorhandenen keyType übereinstimmt, muss das keyType beibehalten werden.
* Wenn ein keyType in der Ressource existiert und in einer Aktualisierung angegeben wird, und der angegebene keyType sich vom vorhandenen keyType unterscheidet, schlägt die Aktualisierung fehl. Definierte Werte sind:
* „generisch“ – Die Anmeldeinformationen sind eine generische Datensammlung. Dies entspricht dem Weglassen eines keyType.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine oder mehrere Zeichenketten müssen im keyStore vorhanden sein.
* Jeder String in der keyStore muss einen in Base64 kodierten Wert haben.
* "passwordHash" - Die Anmeldeinformationen sind ein Passwort-Hash.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Der Name des Berechtigungsnachweises muss eindeutig sein.
* Der Name der Anmeldeinformation muss mit einer gültigen Benutzerressourcen-ID übereinstimmen.
* Der Name des Ausweises darf nicht geändert werden.
* Die entsprechende Benutzerressource muss einen "authProvider"-Wert von "local" haben.
* Eine „Klartext“-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert ein base64-kodiertes Klartextpasswort enthält:
* Das Passwort im Klartext muss den Passwortrichtlinien des Kontos entsprechen.
* Das Passwort wird als Hashwert gespeichert.
* Eine "change"-Zeichenkette muss innerhalb des keyStore mit einem Wert existieren, der eine base64-kodierte Zeichenkette "true" oder "false" enthält.
* Eine Anmeldeinformation des Typs passwordHash kann nur gelöscht werden, wenn die durch den Namen angegebene Benutzer-ID nicht existiert.
* "apikey" - Die Anmeldeinformation ist ein API-Schlüssel.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette namens "apikey" muss innerhalb des keyStore vorhanden sein, deren Wert eine beliebige, base64-kodierte Zeichenkette enthält.
* "kubeconfig" - Die Anmeldeinformationen sind eine kubeconfig.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine "base64"-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert eine base64-kodierte JSON-kubeconfig-Datei enthält.
* Die kubeconfig-Datei darf nur einen einzigen Cluster beschreiben.
* Keine anderen Felder können innerhalb des keyStore existieren.
* "Zertifikat" - Die Anmeldeinformation ist ein PEM-codiertes Zertifikat
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette „certificate“ muss innerhalb des keyStore vorhanden sein, deren Wert ein Base64-kodifiziertes PEM-Zertifikat enthält.
* "privkey" - Die Anmeldeinformationen sind ein PEM-kodierter privater Schlüssel.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine "privkey"-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert einen base64-kodierten PEM-Privatschlüssel enthält.
* "s3" - Gibt an, dass die Anmeldeinformationen für den Zugriff auf Simple Storage Service (S3) bestimmt sind.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette "accessKey" muss innerhalb des keyStore vorhanden sein, mit einem Wert, der einen base64-kodierten S3-Zugriffsschlüssel enthält.
* Eine Zeichenkette "accessSecret" muss innerhalb des keyStore mit einem Wert existieren, der ein base64-kodiertes S3-Zugriffsgeheimnis enthält.




| Gültig | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die beschreibt, ob die Anmeldeinformationen gültig sind. Standardwert, wenn weggelassen, ist „true“. Folgende Werte sind definiert:

* "true" - Die Anmeldeinformationen sind zur Verwendung berechtigt.
* "false" - Die Anmeldeinformationen dürfen nicht verwendet werden.




| validFromTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Anmeldeinformationen gültig sind. Diese werden für die Rotation der Anmeldeinformationen verwendet. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| validUntilTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Anmeldeinformationen nicht mehr gültig sind. Diese werden für die Rotation der Anmeldeinformationen verwendet. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====