---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-entitlements.html 
summary: Alle Berechtigungen auflisten 
---
= Alle Berechtigungen auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/entitlements`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Einschließlich | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "include=id", "include=id,name"

OpenAPI-Beispiele: "id"

* Beispiel: Produkt,entitlementType,entitlementValue,Zuteilung




| Grenze | Zeichenkette | Abfrage | Falsch  a| 
Gibt die maximale Anzahl der Ressourcen an, die beim Auflisten einer Sammlung zurückgegeben werden sollen.

URL-Beispiele: "limit=2"

OpenAPI-Beispiele: "2"



| Filtern | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, welche Felder übereinstimmen müssen, um beim Auflisten einer Sammlung eine Ressource zurückzugeben.

Unterstützte Operatoren sind:

* eq – Gleichheit
* lt/gt – Kleiner als/Größer als
* lte/gte – Kleiner oder gleich/Größer oder gleich


URL-Beispiel: "filter=field%20eq%20%27value%27"

OpenAPI-Beispiele: "field eq 'value'"



| Orderby | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Sortierreihenfolge der Ressourcen beim Auflisten einer Sammlung an.

URL-Beispiele: "orderBy=name", "orderBy=name%20desc"

OpenAPI-Beispiele: "name desc"



| überspringen | Zeichenkette | Abfrage | Falsch  a| 
Gibt die Anzahl der Ressourcen an, die beim Auflisten einer Sammlung übersprungen werden sollen.

URL-Beispiele: "skip=1"

OpenAPI-Beispiele: "1"



| Zählen | Zeichenkette | Abfrage | Falsch  a| 
Gibt an, ob die Gesamtzahl der Ressourcen im Metadatenobjekt zurückgegeben werden soll.

URL-Beispiele: "count=true"

OpenAPI-Beispiele: "true"



| fortfahren |  | Abfrage | Falsch  a| 
Gibt das Token an, von dem aus die Auflistung fortgesetzt werden soll.

URL-Beispiele: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

OpenAPI-Beispiele: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#entitlement_1_0_get_response_body["entitlement_1.0_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-entitlements",
  "version": "1.0",
  "items": [
    [
      "Astra SDS",
      "capacity",
      "2",
      null
    ],
    [
      "Astra Enterprise",
      "clusters",
      "100",
      "5e9fe8f7-4c54-441c-ac94-fd8451f9ca38"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra Metadatenschema


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Wahr  a| 



| CreationZeitstempel | Zeichenkette | Wahr  a| 



| Änderungszeitstempel | Zeichenkette | Wahr  a| 



| Erstellt von | Zeichenkette | Wahr  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
entitlement_1.0_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-entitlement"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Zuweisung | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der ID des Objekts, dem die Berechtigung zugewiesen ist. Nur vorhanden, wenn die Berechtigung zugewiesen ist. Der Inhalt der Zeichenkette wird nicht vom Schema validiert.



| Produkt | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus der Lizenz oder dem Abonnement extrahierten Produktzeichenkette. Der Inhalt der Zeichenkette wurde nicht anhand des Schemas validiert.



| productVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus der Lizenz oder dem Abonnement extrahierten Versionszeichenkette. Zeichenketteninhalt wird nicht vom Schema validiert.



| entitlementType | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem Berechtigungstyp. Diese wird aus der Lizenz oder dem Abonnement extrahiert. Der Inhalt der Zeichenkette wird nicht anhand des Schemas validiert.



| entitlementValue | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der der Berechtigung zugeordneten Kapazität. Zeichenketteninhalt wird nicht durch das Schema validiert.



| entitlementConsumption | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aktuell genutzten Kapazität des Berechtigungsanspruchs. Der Inhalt der Zeichenkette wurde nicht anhand des Schemas validiert.



| sourceLicense | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der Lizenzobjekt-ID, von der die Berechtigung stammt. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| sourceSubscription | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der ID des Abonnementobjekts, aus dem die Berechtigung stammt. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| validFromTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Berechtigung gültig wird. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| validUntilTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Berechtigung nicht mehr gültig ist. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Metadaten | link:#type_astra_metadata["type_astra_metadata"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra Metadatenschema


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====