---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-buckets.html 
summary: Alle Buckets auflisten 
---
= Alle Buckets auflisten
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/buckets`#

Gibt ein JSON-Array aller übereinstimmenden Ressourcen in der Sammlung zurück. Wenn in der Anfrage einzelne Felder angegeben werden, enthält das JSON-Array der Elemente die angeforderten Felder für jede übereinstimmende Ressource in der angegebenen Reihenfolge.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}


|===


== Antwort

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Elemente | array[Beliebig aus: link:#bucket_1_2_get_response_body["bucket_1.2_get_response_body"], array[]] | Wahr  a| 



| Metadaten | link:#type_astra_metadata_list["type_astra_metadata_list"] | Wahr  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-buckets",
  "version": "1.2",
  "items": [
    [
      "4c753e39-25e9-4b36-a8de-69f168aa59cd",
      "Test Bucket",
      "gcp"
    ],
    [
      "d8fd585d-6429-4c08-a308-af193a88eac7",
      "Local",
      "ontap-s3"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidParams | Array[link:#invalidParams["invalidParams"]] | Falsch  a| 
Liste ungültiger Abfrageparameter

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
s3

JSON-Objekt, das die Protokollparameter für Simple Storage Service (S3) bereitstellt. (Verwenden Sie dieses Objekt für alle S3-Typ-Anbieter).

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| serverURL | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit einer URL zum Basispfad des Buckets. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 1023




| bucketName | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem Namen des S3-Buckets. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63


|===
[role="api-collapsible-fifth-title"]
gcp

JSON-Objekt, das Google Cloud-Protokollparameter bereitstellt.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| bucketName | Zeichenkette | Wahr  a| 
JSON-String mit dem Namen des zugrunde liegenden Google Cloud-Bucket-Namens. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63


|===
[role="api-collapsible-fifth-title"]
azure

JSON-Objekt, das Azure-Protokollparameter bereitstellt.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| storageAccount | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit dem Namen des Azure-Speicherkontos. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63




| bucketName | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit dem Namen des zugrunde liegenden Azure-Blobs. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63


|===
[role="api-collapsible-fifth-title"]
bucketParameters

Ein JSON-Objekt, das die für den Zugriff auf den Bucket erforderlichen bucket-anbieterspezifischen Informationen enthält. Die spezifischen Werte in diesem Bucket variieren je nach Anbieter.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| s3 | link:#s3["s3"] | Falsch  a| 
JSON-Objekt, das die Protokollparameter für Simple Storage Service (S3) bereitstellt. (Verwenden Sie dieses Objekt für alle S3-Typ-Anbieter).



| gcp | link:#gcp["gcp"] | Falsch  a| 
JSON-Objekt, das Google Cloud-Protokollparameter bereitstellt.



| azure | link:#azure["azure"] | Falsch  a| 
JSON-Objekt, das Azure-Protokollparameter bereitstellt.

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
bucket_1.2_get_response_body

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-bucket"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für den Bucket. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 256




| Anmeldeinformations-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit der Kennung der Anmeldeinformationen für den Zugriff auf den Bucket. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Zustand | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand des Buckets angibt. Folgende Werte sind definiert:

* „pending“ – Der Bucket ist zur Erkennung vorgesehen
* "verfügbar" – Der Bucket steht zur Benutzung bereit
* „failed“ – Der Bucket befindet sich in einem permanenten Fehlerzustand
* „removed“ – Der Bucket ist derzeit nicht zugänglich
* "unbekannt" – Der Bucket-Status kann nicht ermittelt werden




| stateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Wahr  a| 
Ein JSON-Array mit JSON-Objekten, das zusätzliche Details darüber auflistet, warum der "state" zu "removed" oder "failed" gewechselt hat. Sind keine Details verfügbar, ist dieses Array leer.

* Mindestanzahl: 0




| retentionTime | Nummer | Falsch  a| 
Anzahl der Sekunden, die die Aufbewahrungsdauer einer Datei in diesem Bucket angeben. Folgende Werte sind definiert:

* -1 (Nicht unterstützter Bucket)
* 0 (Keine bekannte Aufbewahrungsrichtlinie)
* 
+
[quote]
____
0 (Bekannte Aufbewahrungsrichtlinie)

____





| Anbieter | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die das Bucket-Protokoll angibt, über das auf den Bucket zugegriffen werden kann. Folgende Werte sind definiert:

* "ontap-s3"
* "storagegrid-s3"
* "generic-s3"
* "gcp"
* "azure"
* "aws"




| bucketParameters | link:#bucketParameters["bucketParameters"] | Wahr  a| 
Ein JSON-Objekt, das die für den Zugriff auf den Bucket erforderlichen bucket-anbieterspezifischen Informationen enthält. Die spezifischen Werte in diesem Bucket variieren je nach Anbieter.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| fortfahren | Zeichenkette | Falsch  a| 



| Zählen | Nummer | Falsch  a| 



| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
====