---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-topology-v1-buckets.html 
summary: Einen neuen Bucket erstellen 
---
= Einen neuen Bucket erstellen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/buckets`#

Gibt die gewünschten Werte für die zu erstellende Bucket-API-Ressource an.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}


|===


== Anfragetext

Gibt die gewünschten Werte für die zu erstellende Bucket-API-Ressource an.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-bucket"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"




| Name | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für den Bucket. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 256




| Anmeldeinformations-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit der Kennung der Anmeldeinformationen für den Zugriff auf den Bucket. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Anbieter | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die das Bucket-Protokoll angibt, über das auf den Bucket zugegriffen werden kann. Folgende Werte sind definiert:

* "ontap-s3"
* "storagegrid-s3"
* "generic-s3"
* "gcp"
* "azure"
* "aws"




| bucketParameters | link:#bucketParameters["bucketParameters"] | Wahr  a| 
Ein JSON-Objekt, das die für den Zugriff auf den Bucket erforderlichen bucket-anbieterspezifischen Informationen enthält. Die spezifischen Werte in diesem Bucket variieren je nach Anbieter.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-bucket",
  "version": "1.2",
  "name": "Test Bucket",
  "credentialID": "d5b3854c-38de-42c6-9269-b5c052aba76f",
  "provider": "gcp",
  "bucketParameters": {
    "gcp": {
      "bucketName": "bucketName"
    }
  }
}
----
====


== Antwort

[source]
----
Status: 201, Returns the newly created bucket resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-bucket"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für den Bucket. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 256




| Anmeldeinformations-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit der Kennung der Anmeldeinformationen für den Zugriff auf den Bucket. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Zustand | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand des Buckets angibt. Folgende Werte sind definiert:

* „pending“ – Der Bucket ist zur Erkennung vorgesehen
* "verfügbar" – Der Bucket steht zur Benutzung bereit
* „failed“ – Der Bucket befindet sich in einem permanenten Fehlerzustand
* „removed“ – Der Bucket ist derzeit nicht zugänglich
* "unbekannt" – Der Bucket-Status kann nicht ermittelt werden




| stateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Wahr  a| 
Ein JSON-Array mit JSON-Objekten, das zusätzliche Details darüber auflistet, warum der "state" zu "removed" oder "failed" gewechselt hat. Sind keine Details verfügbar, ist dieses Array leer.

* Mindestanzahl: 0




| retentionTime | Nummer | Falsch  a| 
Anzahl der Sekunden, die die Aufbewahrungsdauer einer Datei in diesem Bucket angeben. Folgende Werte sind definiert:

* -1 (Nicht unterstützter Bucket)
* 0 (Keine bekannte Aufbewahrungsrichtlinie)
* 
+
[quote]
____
0 (Bekannte Aufbewahrungsrichtlinie)

____





| Anbieter | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die das Bucket-Protokoll angibt, über das auf den Bucket zugegriffen werden kann. Folgende Werte sind definiert:

* "ontap-s3"
* "storagegrid-s3"
* "generic-s3"
* "gcp"
* "azure"
* "aws"




| bucketParameters | link:#bucketParameters["bucketParameters"] | Wahr  a| 
Ein JSON-Objekt, das die für den Zugriff auf den Bucket erforderlichen bucket-anbieterspezifischen Informationen enthält. Die spezifischen Werte in diesem Bucket variieren je nach Anbieter.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-bucket",
  "version": "1.2",
  "id": "9b296ce0-c545-5022-acfa-1980c5aaea97",
  "name": "Test Bucket",
  "credentialID": "8f039324-7795-40bf-a5ca-4442580f7ab0",
  "state": "available",
  "stateDetails": [],
  "provider": "gcp",
  "bucketParameters": {
    "gcp": {
      "bucketName": "bucketName"
    }
  },
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
s3

JSON-Objekt, das die Protokollparameter für Simple Storage Service (S3) bereitstellt. (Verwenden Sie dieses Objekt für alle S3-Typ-Anbieter).

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| serverURL | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit einer URL zum Basispfad des Buckets. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 1023




| bucketName | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit dem Namen des S3-Buckets. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63


|===
[role="api-collapsible-fifth-title"]
gcp

JSON-Objekt, das Google Cloud-Protokollparameter bereitstellt.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| bucketName | Zeichenkette | Wahr  a| 
JSON-String mit dem Namen des zugrunde liegenden Google Cloud-Bucket-Namens. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63


|===
[role="api-collapsible-fifth-title"]
azure

JSON-Objekt, das Azure-Protokollparameter bereitstellt.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| storageAccount | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit dem Namen des Azure-Speicherkontos. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63




| bucketName | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit dem Namen des zugrunde liegenden Azure-Blobs. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 63


|===
[role="api-collapsible-fifth-title"]
bucketParameters

Ein JSON-Objekt, das die für den Zugriff auf den Bucket erforderlichen bucket-anbieterspezifischen Informationen enthält. Die spezifischen Werte in diesem Bucket variieren je nach Anbieter.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| s3 | link:#s3["s3"] | Falsch  a| 
JSON-Objekt, das die Protokollparameter für Simple Storage Service (S3) bereitstellt. (Verwenden Sie dieses Objekt für alle S3-Typ-Anbieter).



| gcp | link:#gcp["gcp"] | Falsch  a| 
JSON-Objekt, das Google Cloud-Protokollparameter bereitstellt.



| azure | link:#azure["azure"] | Falsch  a| 
JSON-Objekt, das Azure-Protokollparameter bereitstellt.

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====