---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-credentials.html 
summary: Neue Anmeldeinformationen erstellen 
---
= Neue Anmeldeinformationen erstellen
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials`#

Gibt die gewünschten Werte für die zu erstellende Credential-API-Ressource an.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}


|===


== Anfragetext

Gibt die gewünschten Werte für die zu erstellende Credential-API-Ressource an.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-credential"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit einem benutzerdefinierten Namen. Beim Erstellen von Anmeldeinformationen für einen Benutzer wird der Name auf die UUID dieses Benutzers gesetzt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 127




| keyType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem optionalen, vom Benutzer festgelegten Datenvalidierungstypdeskriptor für den Inhalt der keyStore. Erweiterte Aktualisierungseinschränkungen:

* Wenn ein keyType in der Ressource nicht existiert und in einem Update nicht angegeben wird, darf der keyType in der aktualisierten Ressource nicht mehr existieren.
* Wenn ein keyType in der Ressource nicht existiert und in einer Aktualisierung angegeben wird, muss der keyType der Ressource hinzugefügt und eine Validierung durchgeführt werden. Wenn die Validierung fehlschlägt, schlägt die Aktualisierung fehl.
* Wenn ein keyType in der Ressource existiert und in einem Update nicht angegeben wird, muss der keyType beibehalten werden.
* Wenn ein keyType in der Ressource existiert und in einem Update angegeben wird und das angegebene keyType mit dem vorhandenen keyType übereinstimmt, muss das keyType beibehalten werden.
* Wenn ein keyType in der Ressource existiert und in einer Aktualisierung angegeben wird, und der angegebene keyType sich vom vorhandenen keyType unterscheidet, schlägt die Aktualisierung fehl. Definierte Werte sind:
* „generisch“ – Die Anmeldeinformationen sind eine generische Datensammlung. Dies entspricht dem Weglassen eines keyType.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine oder mehrere Zeichenketten müssen im keyStore vorhanden sein.
* Jeder String in der keyStore muss einen in Base64 kodierten Wert haben.
* "passwordHash" - Die Anmeldeinformationen sind ein Passwort-Hash.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Der Name des Berechtigungsnachweises muss eindeutig sein.
* Der Name der Anmeldeinformation muss mit einer gültigen Benutzerressourcen-ID übereinstimmen.
* Der Name des Ausweises darf nicht geändert werden.
* Die entsprechende Benutzerressource muss einen "authProvider"-Wert von "local" haben.
* Eine „Klartext“-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert ein base64-kodiertes Klartextpasswort enthält:
* Das Passwort im Klartext muss den Passwortrichtlinien des Kontos entsprechen.
* Das Passwort wird als Hashwert gespeichert.
* Eine "change"-Zeichenkette muss innerhalb des keyStore mit einem Wert existieren, der eine base64-kodierte Zeichenkette "true" oder "false" enthält.
* Eine Anmeldeinformation des Typs passwordHash kann nur gelöscht werden, wenn die durch den Namen angegebene Benutzer-ID nicht existiert.
* "apikey" - Die Anmeldeinformation ist ein API-Schlüssel.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette namens "apikey" muss innerhalb des keyStore vorhanden sein, deren Wert eine beliebige, base64-kodierte Zeichenkette enthält.
* "kubeconfig" - Die Anmeldeinformationen sind eine kubeconfig.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine "base64"-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert eine base64-kodierte JSON-kubeconfig-Datei enthält.
* Die kubeconfig-Datei darf nur einen einzigen Cluster beschreiben.
* Keine anderen Felder können innerhalb des keyStore existieren.
* "Zertifikat" - Die Anmeldeinformation ist ein PEM-codiertes Zertifikat
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette „certificate“ muss innerhalb des keyStore vorhanden sein, deren Wert ein Base64-kodifiziertes PEM-Zertifikat enthält.
* "privkey" - Die Anmeldeinformationen sind ein PEM-kodierter privater Schlüssel.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine "privkey"-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert einen base64-kodierten PEM-Privatschlüssel enthält.
* "s3" - Gibt an, dass die Anmeldeinformationen für den Zugriff auf Simple Storage Service (S3) bestimmt sind.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette "accessKey" muss innerhalb des keyStore vorhanden sein, mit einem Wert, der einen base64-kodierten S3-Zugriffsschlüssel enthält.
* Eine Zeichenkette "accessSecret" muss innerhalb des keyStore mit einem Wert existieren, der ein base64-kodiertes S3-Zugriffsgeheimnis enthält.




| keyStore | link:#keyStore["keyStore"] | Wahr  a| 
JSON-Objekt mit JSON-Zeichenketten. Jede Zeichenkette in keyStore repräsentiert einen Teil der Anmeldeinformationen. Der Name jeder Zeichenkette steht für den entsprechenden Teil der Anmeldeinformationen, und der zugehörige Schlüssel-Wert speichert den Wert dieses Teils im Base64-Format. Folgende Werte sind definiert:

* Entspricht dem Base64-kodierten Datenschema. Es gibt keine Beschränkungen hinsichtlich der Länge der Zeichenketten.




| Gültig | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die beschreibt, ob die Anmeldeinformationen gültig sind. Standardwert, wenn weggelassen, ist „true“. Folgende Werte sind definiert:

* "true" - Die Anmeldeinformationen sind zur Verwendung berechtigt.
* "false" - Die Anmeldeinformationen dürfen nicht verwendet werden.




| validFromTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Anmeldeinformationen gültig sind. Diese werden für die Rotation der Anmeldeinformationen verwendet. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| validUntilTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Anmeldeinformationen nicht mehr gültig sind. Diese werden für die Rotation der Anmeldeinformationen verwendet. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "name": "myCert",
  "keyStore": {
    "privKey": "SGkh",
    "pubKey": "VGhpcyBpcyBhbiBleGFtcGxlLg=="
  }
}
----
====


== Antwort

[source]
----
Status: 201, Returns the newly created credential resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-credential"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit einem benutzerdefinierten Namen. Beim Erstellen von Anmeldeinformationen für einen Benutzer wird der Name auf die UUID dieses Benutzers gesetzt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 127




| keyType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem optionalen, vom Benutzer festgelegten Datenvalidierungstypdeskriptor für den Inhalt der keyStore. Erweiterte Aktualisierungseinschränkungen:

* Wenn ein keyType in der Ressource nicht existiert und in einem Update nicht angegeben wird, darf der keyType in der aktualisierten Ressource nicht mehr existieren.
* Wenn ein keyType in der Ressource nicht existiert und in einer Aktualisierung angegeben wird, muss der keyType der Ressource hinzugefügt und eine Validierung durchgeführt werden. Wenn die Validierung fehlschlägt, schlägt die Aktualisierung fehl.
* Wenn ein keyType in der Ressource existiert und in einem Update nicht angegeben wird, muss der keyType beibehalten werden.
* Wenn ein keyType in der Ressource existiert und in einem Update angegeben wird und das angegebene keyType mit dem vorhandenen keyType übereinstimmt, muss das keyType beibehalten werden.
* Wenn ein keyType in der Ressource existiert und in einer Aktualisierung angegeben wird, und der angegebene keyType sich vom vorhandenen keyType unterscheidet, schlägt die Aktualisierung fehl. Definierte Werte sind:
* „generisch“ – Die Anmeldeinformationen sind eine generische Datensammlung. Dies entspricht dem Weglassen eines keyType.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine oder mehrere Zeichenketten müssen im keyStore vorhanden sein.
* Jeder String in der keyStore muss einen in Base64 kodierten Wert haben.
* "passwordHash" - Die Anmeldeinformationen sind ein Passwort-Hash.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Der Name des Berechtigungsnachweises muss eindeutig sein.
* Der Name der Anmeldeinformation muss mit einer gültigen Benutzerressourcen-ID übereinstimmen.
* Der Name des Ausweises darf nicht geändert werden.
* Die entsprechende Benutzerressource muss einen "authProvider"-Wert von "local" haben.
* Eine „Klartext“-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert ein base64-kodiertes Klartextpasswort enthält:
* Das Passwort im Klartext muss den Passwortrichtlinien des Kontos entsprechen.
* Das Passwort wird als Hashwert gespeichert.
* Eine "change"-Zeichenkette muss innerhalb des keyStore mit einem Wert existieren, der eine base64-kodierte Zeichenkette "true" oder "false" enthält.
* Eine Anmeldeinformation des Typs passwordHash kann nur gelöscht werden, wenn die durch den Namen angegebene Benutzer-ID nicht existiert.
* "apikey" - Die Anmeldeinformation ist ein API-Schlüssel.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette namens "apikey" muss innerhalb des keyStore vorhanden sein, deren Wert eine beliebige, base64-kodierte Zeichenkette enthält.
* "kubeconfig" - Die Anmeldeinformationen sind eine kubeconfig.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine "base64"-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert eine base64-kodierte JSON-kubeconfig-Datei enthält.
* Die kubeconfig-Datei darf nur einen einzigen Cluster beschreiben.
* Keine anderen Felder können innerhalb des keyStore existieren.
* "Zertifikat" - Die Anmeldeinformation ist ein PEM-codiertes Zertifikat
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette „certificate“ muss innerhalb des keyStore vorhanden sein, deren Wert ein Base64-kodifiziertes PEM-Zertifikat enthält.
* "privkey" - Die Anmeldeinformationen sind ein PEM-kodierter privater Schlüssel.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine "privkey"-Zeichenkette muss innerhalb des keyStore vorhanden sein, deren Wert einen base64-kodierten PEM-Privatschlüssel enthält.
* "s3" - Gibt an, dass die Anmeldeinformationen für den Zugriff auf Simple Storage Service (S3) bestimmt sind.
* Die erweiterte Validierung wird wie folgt durchgeführt:
* Eine Zeichenkette "accessKey" muss innerhalb des keyStore vorhanden sein, mit einem Wert, der einen base64-kodierten S3-Zugriffsschlüssel enthält.
* Eine Zeichenkette "accessSecret" muss innerhalb des keyStore mit einem Wert existieren, der ein base64-kodiertes S3-Zugriffsgeheimnis enthält.




| Gültig | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die beschreibt, ob die Anmeldeinformationen gültig sind. Standardwert, wenn weggelassen, ist „true“. Folgende Werte sind definiert:

* "true" - Die Anmeldeinformationen sind zur Verwendung berechtigt.
* "false" - Die Anmeldeinformationen dürfen nicht verwendet werden.




| validFromTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Anmeldeinformationen gültig sind. Diese werden für die Rotation der Anmeldeinformationen verwendet. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| validUntilTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Anmeldeinformationen nicht mehr gültig sind. Diese werden für die Rotation der Anmeldeinformationen verwendet. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "id": "58e26f6a-a631-5122-8e0e-7afe306675c0",
  "name": "myCert",
  "valid": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
keyStore

JSON-Objekt mit JSON-Zeichenketten. Jede Zeichenkette in keyStore repräsentiert einen Teil der Anmeldeinformationen. Der Name jeder Zeichenkette steht für den entsprechenden Teil der Anmeldeinformationen, und der zugehörige Schlüssel-Wert speichert den Wert dieses Teils im Base64-Format. Folgende Werte sind definiert:

* Entspricht dem Base64-kodierten Datenschema. Es gibt keine Beschränkungen hinsichtlich der Länge der Zeichenketten.


Hash-Zuordnung von Zeichenketten zu Zeichenketten

[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====