---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-k8s-v1-apps-executionhookoverrides.html 
summary: Erstellen Sie eine neue Ausführungshook-Override-Ressource für eine App 
---
= Erstellen Sie eine neue Ausführungshook-Override-Ressource für eine App
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHookOverrides`#

Gibt die gewünschten Werte für die zu erstellende Execution Hook Override API-Ressource an.


CAUTION: Diese Funktion ist veraltet.



== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| App-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten App-Ressource

|===


== Anfragetext

Gibt die gewünschten Werte für die zu erstellende Execution Hook Override API-Ressource an.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-executionHookOverride"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"




| executionHookID | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der ID eines Ausführungs-Hooks. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema. Erlaubt ausschließlich die executionHookID einer Ausführungshook-Ressource mit einem hookType-Wert von "netapp".




| aktiviert | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob der Ausführungshook für die angegebene Anwendung aktiviert ist. Folgende Werte sind definiert:

* "true" - Der Ausführungs-Hook ist aktiviert und wird in der angegebenen Reihenfolge ausgeführt
* "false" - Der Ausführungshook ist deaktiviert und kann nicht ausgeführt werden




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverride",
  "version": "1.0",
  "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
  "enabled": "false"
}
----
====


== Antwort

[source]
----
Status: 201, Returns the newly created executionHookOverride resource in the JSON response body.
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-executionHookOverride"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"




| id | Zeichenkette | Wahr  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| executionHookID | Zeichenkette | Wahr  a| 
JSON-Zeichenkette mit der ID eines Ausführungs-Hooks. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema. Erlaubt ausschließlich die executionHookID einer Ausführungshook-Ressource mit einem hookType-Wert von "netapp".




| aktiviert | Zeichenkette | Wahr  a| 
JSON-Zeichenkette, die angibt, ob der Ausführungshook für die angegebene Anwendung aktiviert ist. Folgende Werte sind definiert:

* "true" - Der Ausführungs-Hook ist aktiviert und wird in der angegebenen Reihenfolge ausgeführt
* "false" - Der Ausführungshook ist deaktiviert und kann nicht ausgeführt werden




| App-ID | Zeichenkette | Wahr  a| 
JSON-Zeichenfolge mit der zugehörigen ID der Anwendung, mit der die Überschreibung verknüpft ist. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Wahr  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverride",
  "version": "1.0",
  "id": "c11af802-5e53-5897-8cd9-2de730494be3",
  "executionHookID": "eb863cc6-0d9a-454d-8ef7-81b7cac91929",
  "enabled": "false",
  "appID": "4b43c2f7-bffa-4f60-b595-d98a05b64bc9",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====