---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-licenses-.html 
summary: Eine Lizenz ändern 
---
= Eine Lizenz ändern
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/licenses/{license_id}`#

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Die Berechtigungen werden neu berechnet, um die über die Entitlement-API sichtbaren Lizenzberechtigungen hinzuzufügen oder zusammenzuführen.




== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| Lizenz-ID | Zeichenkette | Pfad | Wahr  a| 
ID der aufzulistenden Lizenzsammlung

|===


== Anfragetext

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Die Berechtigungen werden neu berechnet, um die über die Entitlement-API sichtbaren Lizenzberechtigungen hinzuzufügen oder zusammenzuführen.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-license"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"




| id | Zeichenkette | Falsch  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Zuweisung | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit einer ID, die angibt, wem die Lizenz zugeordnet ist. Nur vorhanden, wenn die Lizenz zugeordnet ist. Bei Astra Control Center-Lizenzen muss dieses Feld die Konto-ID enthalten und mit der in der POST-URI angegebenen Konto-ID übereinstimmen. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Host-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer Host-Kennung, an die eine Lizenz gebunden ist. Nur vorhanden, wenn die Lizenz host-locked ist. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| Geräte-Anmeldeinformationen-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit der Kennung der deviceCredential, die mit der Credential API verknüpft ist. Nur für Astra Data Store-Lizenzen vorhanden. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| isEvaluation | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, ob es sich um eine Evaluierungslizenz handelt. Folgende Werte sind definiert:

* "true"
* "false"




| licenseProtocol | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem aus der Lizenz extrahierten Lizenzprotokoll. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| licenseText | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer Base64-kodierten Darstellung der Lizenz-JSON-Datei, wie sie vom NetApp Lizenzsystem abgerufen wurde. Diese muss in der ursprünglichen Byte-Reihenfolge angegeben werden, um die Signaturprüfung zu ermöglichen. Folgende Werte sind definiert:

* Entspricht dem Base64-kodierten Datenschema




| validFromTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Lizenz gültig wird. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| validUntilTimestamp | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann die Lizenz nicht mehr gültig ist. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Produkt | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Produktzeichenkette. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| productVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Versionszeichenkette. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| Produkt-SN | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Seriennummer. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| Merkmale | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem aus der Lizenz extrahierten Paketwert. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| Kapazität | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus der Lizenz extrahierten Kapazität.



| capacity2 | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die die aus der Lizenz extrahierte Sekundärkapazität enthält.



| Add-ons | Array[link:#addons["Add-ons"]] | Falsch  a| 
JSON-Array von JSON-Objekten, das die Liste der Add-ons aus der Lizenz enthält. Ein Add-on ist eine Lizenzänderung, die zu einem möglichen zukünftigen Zeitpunkt in Kraft tritt.



| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-license",
  "version": "1.0",
  "allocation": "4185d09b-6687-4801-a832-c005a9d94f41",
  "licenseText": "ewogICAic3RhdHVzUmVzcCI6ewogMTYwNzAwIgp9"
}
----
====


== Antwort

[source]
----
Status: 204, Indicates if the license resource was updated.
----


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
Add-ons

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| startDate | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann dieses Add-on gültig wird. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| endDate | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Zeitstempel, der angibt, wann dieses Add-on nicht mehr gültig ist. Definierte Werte sind:

* Entspricht dem ISO-8601 Datums- und Zeitschema




| Merkmale | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Liste der Funktionen, die diesem Add-on zugeordnet sind. Folgende Werte sind definiert:

* Der Zeichenketteninhalt wurde vom Schema nicht validiert.




| Kapazität | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der aus dem Add-on extrahierten Kapazität. Definierte Werte sind:

* Zeichenketteninhalte wurden vom Schema nicht validiert




| licenseProtocol | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit dem Lizenzprotokoll dieses Add-ons. Folgende Werte sind definiert:

* Zeichenketteninhalte wurden vom Schema nicht validiert


|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====