---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-k8s-v1-apps-appmirrors-.html 
summary: Eine AppMirror-Ressource für eine App ändern 
---
= Eine AppMirror-Ressource für eine App ändern
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appMirrors/{appMirror_id}`#

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Verschiedene Nebenwirkungen basierend auf desiredState.




== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| App-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten App-Ressource



| appMirror_id | Zeichenkette | Pfad | Wahr  a| 
ID der appMirror-Sammlung, die aufgelistet werden soll

|===


== Anfragetext

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Verschiedene Nebenwirkungen basierend auf desiredState.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-appMirror"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"




| id | Zeichenkette | Falsch  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| sourceAppID | Zeichenkette | Falsch  a| 
Kennung der Quellanwendung. Wird nur aktualisiert, wenn die sourceAppID mit der destinationAppID ausgetauscht wird. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Quell-Cluster-ID | Zeichenkette | Falsch  a| 
Kennung des verwalteten Clusters, auf dem die Quellanwendung gehostet wird. Dieses Feld ist schreibgeschützt und wird anhand des Host-Clusters der Quellanwendung ermittelt. Wird es bei einem Update angegeben, muss es mit der Cluster-ID der Quellanwendung übereinstimmen, daher kann es sich nur ändern, wenn die sourceAppID mit der destinationAppID vertauscht wird. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| ZielAppID | Zeichenkette | Falsch  a| 
Kennung der Zielanwendung. Kann beim Erstellen nicht angegeben werden, da im Rahmen der Beziehungsinitialisierung eine neue App-ID generiert wird. Kann nur aktualisiert werden, wenn die sourceAppID mit der destinationAppID ausgetauscht wird. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Ziel-Cluster-ID | Zeichenkette | Falsch  a| 
Kennung des verwalteten Clusters, der die Zielanwendung hostet. Muss beim Erstellen angegeben werden, da sie bestimmt, auf welchem Cluster die Zielanwendung erstellt wird. Wird sie beim Aktualisieren angegeben, muss sie mit der Cluster-ID der Zielanwendung übereinstimmen, daher kann sie sich nur ändern, wenn sourceAppID mit destinationAppID vertauscht wird. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| namespaceMapping | Array[link:#namespaceMapping["namespaceMapping"]] | Falsch  a| 
Der oder die Namespaces, die beim Erstellen der Zielanwendung verwendet werden sollen, entsprechend den Namespaces der Quellanwendung. Jedes JSON-Objekt enthält die Felder „clusterID“ und „namespaces“, wobei der Wert von „clusterID“ die JSON-String-ID des Quell- oder Ziel-Cluster ist und der Wert von „namespaces“ ein JSON-Array von JSON-Strings ist. Für jeden Cluster muss genau ein JSON-Objekt vorhanden sein, und die Namespaces werden über ihren Index korreliert. Falls nicht angegeben, wird derselbe Namespace vom Quell-Cluster auch im Ziel-Cluster verwendet. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 2




| storageClasses | Array[link:#storageClasses["storageClasses"]] | Falsch  a| 
Die Speicherklasse, die auf dem Ziel-Cluster beim Erstellen neuer Persistent Volume Claims (PVCs) verwendet werden soll. Jedes JSON-Objekt enthält die Felder „clusterID“ und „storageClassName“, wobei der Wert von „clusterID“ die JSON-String-ID des Quell- oder Ziel-Cluster ist und „storageClassName“ die Speicherklasse ist, die beim Erstellen von PVCs auf diesem Cluster verwendet werden soll. Wenn kein Wert angegeben wird oder der Wert für einen Cluster fehlt, wird die Standard-Speicherklasse für diesen Cluster verwendet. Folgende Werte sind definiert:

* Mindestlänge: 0
* Maximale Länge: 2




| Zustand | Zeichenkette | Falsch  a| 
Der Status der Beziehung. Definierte Werte sind:

* „establishing“ – Die Beziehung wird gerade hergestellt.
* „Etabliert“ – Die Beziehung ist hergestellt.
* "failingOver" - Das Failover der Anwendung auf den Ziel-Cluster wird durchgeführt.
* "failedOver" - Das Failover der Anwendung auf den Ziel-Cluster wurde abgeschlossen.
* "Löschen" – Die durch die Beziehung erstellten Ressourcen werden bereinigt.
* "gelöscht" - Die Beziehung wurde bereinigt und gelöscht.




| stateTransitions | Array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falsch  a| 
Zulässige Zustandsübergänge. Für diese Ressource sind folgende Zustandsübergänge möglich:

* "establishing": "established", "deleting"
* "established": "failingOver", "deleting"
* "failingOver": "failedOver", "Löschen"
* "failedOver": "einrichten", "löschen"
* "Löschen": "gelöscht"
* "gelöscht":




| stateDesired | Zeichenkette | Falsch  a| 
Der gewünschte Zustand der Beziehung. Bei der Erstellung ist nur der Wert „etabliert“ gültig. Folgende Werte sind definiert:

* „Etabliert“ – Die Beziehung ist hergestellt.
* "failedOver" - Das Failover der Anwendung auf den Ziel-Cluster wurde abgeschlossen.
* "gelöscht" - Die Beziehung wurde erfolgreich bereinigt und gelöscht.




| stateAllowed | Array[string] | Falsch  a| 
Zustände, die in einem bestimmten Zustand angefordert werden können. Die folgenden Zustände können in jedem definierten Zustand angefordert werden:

* "establishing": "etabliert", "gelöscht"
* "established": "failedOver", "deleted"
* "failingOver": "failedOver", "gelöscht"
* "failedOver": "etabliert", "gelöscht"
* "Löschen": "gelöscht"
* "gelöscht": "gelöscht"




| stateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falsch  a| 
Zusätzliche Details zum aktuellen Zustand, einschließlich der Gründe für dessen Erreichen. Sind keine Details verfügbar, ist dieses Array leer. Folgende Werte sind definiert:

* Mindestanzahl: 0




| transferState | Zeichenkette | Falsch  a| 
Status der aktuellen oder letzten Snapshot-Übertragung. Folgende Werte sind definiert:

* „Übertragung läuft“ – Ein neuer Snapshot wurde erstellt und wird nun in den Ziel-Cluster repliziert. Dieser Status umfasst auch Übertragungen, die bei vorherigen Versuchen fehlgeschlagen sind und nun wiederholt werden.
* "Leerlauf" - Derzeit findet keine Übertragung statt.




| transferStateTransitions | Array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falsch  a| 
Zulässige Zustandsübergänge von einem vorgegebenen Zustand aus. Für diese Ressource sind folgende Zustandsübergänge möglich:

* "transferring": "Leerlauf"
* "idle": "transferring"




| transferStateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falsch  a| 
Zusätzliche Details zum aktuellen Zustand, einschließlich der Gründe für dessen Erreichen. Sind keine Details verfügbar, ist dieses Array leer. Folgende Werte sind definiert:

* Mindestanzahl: 0




| healthState | Zeichenkette | Falsch  a| 
Gesundheitszustand der Ressource. Definierte Werte sind:

* „unbestimmt“ – Der Zustand der Ressource kann nicht bestimmt werden (z. B. aufgrund fehlender Verbindung)
* „normal“ – Die Ressource weist keine bekannten Probleme auf und kann Dienste gemäß der Schnittstellenspezifikation bereitstellen.
* "Warnung" – Die Ressource weist bekannte Probleme auf, die sie jedoch nicht daran hindern, Dienste gemäß der Schnittstellenspezifikation bereitzustellen.
* "kritisch" – Die Ressource weist bekannte Probleme auf, die sie daran hindern, Dienste gemäß der Schnittstellenspezifikation bereitzustellen.




| healthStateTransitions | Array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falsch  a| 
Zulässige Zustandsübergänge von einem vorgegebenen Zustand aus. Für diese Ressource sind folgende Zustandsübergänge möglich:

* "indeterminate": "normal", "Warnung", "kritisch"
* "normal": "unbestimmt", "Warnung", "kritisch"
* "Warnung": "unbestimmt", "normal", "kritisch"
* "kritisch": "unbestimmt", "normal", "Warnung"




| healthStateDetails | Array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falsch  a| 
Zusätzliche Details zum aktuellen Zustand, einschließlich der Gründe für dessen Erreichen. Sind keine Details verfügbar, ist dieses Array leer. Folgende Werte sind definiert:

* Mindestanzahl: 0




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appMirror",
  "version": "1.1",
  "stateDesired": "failedOver"
}
----
====


== Antwort

[source]
----
Status: 204, Indicates if the appMirror resource was updated.
----


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
namespaceMapping

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Cluster-ID | Zeichenkette | Falsch  a| 
Kennung des Clusters, für den die Namensräume angegeben sind. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| Namensräume | Array[string] | Falsch  a| 
Liste der im Cluster zu verwendenden Namensräume. Korreliert mit der anderen Namensraumliste des Clusters über den Index. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63
* Entspricht dem DNS 1123 Label Schema




| Rolle | Zeichenkette | Falsch  a| 
Die anfängliche Rolle für diese Namespace-Definition. Dieser Parameter ist optional, außer bei Verwendung einer Replikationskonfiguration innerhalb desselben Clusters. Folgende Werte sind definiert:

* "Quelle"
* "Ziel"


|===
[role="api-collapsible-fifth-title"]
storageClasses

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Cluster-ID | Zeichenkette | Falsch  a| 
Kennung des Clusters, für den die Speicherklasse angegeben ist. Folgende Werte sind definiert:

* Entspricht dem Astra-Identifikatorschema




| storageClassName | Zeichenkette | Falsch  a| 
Name der Speicherklasse, die beim Erstellen von PVCs auf dem in „clusterID“ angegebenen Cluster verwendet werden soll. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 255




| Rolle | Zeichenkette | Falsch  a| 
Die anfängliche Rolle für diese Speicherklassendefinition. Dieser Parameter ist optional, außer bei Verwendung einer Replikationskonfiguration innerhalb desselben Clusters. Folgende Werte sind definiert:

* "Quelle"
* "Ziel"


|===
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| aus | Zeichenkette | Wahr  a| 



| : | Array[string] | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====