---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-executionhooks-.html 
summary: Einen Ausführungs-Hook modifizieren 
---
= Einen Ausführungs-Hook modifizieren
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/executionHooks/{executionHook_id}`#

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Die Aktualisierung eines bestehenden Ausführungs-Hooks wirkt sich auf alle zukünftigen Aktionen von Anwendungen aus, die den aktualisierten Ausführungs-Hook verwenden.




== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| executionHook_id | Zeichenkette | Pfad | Wahr  a| 
ID der executionHook-Sammlung, die aufgelistet werden soll

|===


== Anfragetext

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Die Aktualisierung eines bestehenden Ausführungs-Hooks wirkt sich auf alle zukünftigen Aktionen von Anwendungen aus, die den aktualisierten Ausführungs-Hook verwenden.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-executionHook"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | Zeichenkette | Falsch  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| Name | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für die Ressource. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63 Name muss über alle Ausführungs-Hook-Ressourcen hinweg eindeutig sein.




| hookType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die den Hook-Typ definiert. Definierte Werte sind:

* "netapp" - NetApp bereitgestellter Ausführungs-Hook.
* „custom“ – An eine bestimmte App-ID gebunden. Ausführungshook-Ressourcen mit hookType „netapp“ sind schreibgeschützt.




| matchingCriteria | Array[link:#matchingCriteria["matchingCriteria"]] | Falsch  a| 
JSON-Array von JSON-Objekten, die die Übereinstimmungskriterien für den Ausführungs-Hook beschreiben. Wenn mehrere matchingCriteria angegeben werden, wird eine logische UND-Verknüpfung auf die Kriterien angewendet. Definierte Werte sind:

* Mindestanzahl: 0
* Maximale Elemente: 10




| Aktion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, welche Aktion der Ausführungs-Hook ausführt, sofern die Übereinstimmungskriterien erfüllt sind. Definierte Werte sind:

* "Schnappschuss"
* "Backup"
* "wiederherstellen"
* "Failover"




| Bühne | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die die Phase der Aktion angibt, in der der Hook ausgeführt wird. Definierte Werte sind:

* "pre" - Der Ausführungs-Hook wird vor der angegebenen Aktion ausgeführt.
* „post“ – Der Ausführungs-Hook wird nach der angegebenen Aktion ausgeführt. Die Werte für die Aktion „snapshot“ sind „pre“ und „post“. Die Werte für die Aktion „backup“ sind „pre“ und „post“. Der Wert für die Aktion „restore“ ist „post“. Der Wert für die Aktion „failover“ ist „post“.




| hookSourceID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der Hook-Quell-ID, die über diesen Ausführungs-Hook ausgeführt wird. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| Argumente | Array[string] | Falsch  a| 
JSON-Array von JSON-Zeichenketten für die Argumente der Quelle. Definierte Werte sind:

* Mindestanzahl: 0
* Maximale Elemente: 16
* Mindestlänge: 0
* Maximale Länge: 127




| App-ID | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit der zugehörigen ID der Anwendung, mit der dieser Hook verknüpft ist. Im Wesentlichen weitere festgelegte Übereinstimmungskriterien, falls festgelegt. Definierte Werte sind:

* Entspricht dem Astra-Identifikatorschema




| aktiviert | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die angibt, ob der Ausführungs-Hook aktiviert ist. Folgende Werte sind definiert:

* "true" - Der Ausführungshook ist aktiviert und wird wie angegeben ausgeführt.
* "false" - Der Ausführungshook ist deaktiviert und wird niemals ausgeführt. Der Standardwert ist "true".




| description | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einer benutzerdefinierten Beschreibung der Hook-Quelle. Definierte Werte sind:

* Mindestlänge: 0
* Maximale Länge: 511




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "arguments": [
    "freeze",
    "10"
  ]
}
----
====


== Antwort

[source]
----
Status: 204, Indicates if the executionHook resource was updated.
----


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die den Typ der Übereinstimmungskriterien identifiziert.



| Wert | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem regulären Ausdruck für den angegebenen Übereinstimmungstyp. Regex-Syntax: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====