---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-topology-v1-storagebackends-.html 
summary: Ein Storage-Backend modifizieren 
---
= Ein Storage-Backend modifizieren
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/storageBackends/{storageBackend_id}`#

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Die Angabe einer Konfigurationsversion führt dazu, dass speicher-backend-spezifische Konfigurationsänderungen angewendet werden, was auch die Erstinstallation eines Speicher-Backends umfassen kann.
* Die Angabe einer Konfigurationsversion kann dazu führen, dass storageClass Ressourcen hinzugefügt, geändert oder entfernt werden.




== Parameter

[cols="5*"]
|===
| Name | Typ | In | Erforderlich | Beschreibung 


| Konto-ID | Zeichenkette | Pfad | Wahr  a| 
ID der übergeordneten Kontoressource

* Beispiel: {{.Account}}




| storageBackend_id | Zeichenkette | Pfad | Wahr  a| 
ID der storageBackend Sammlung, die aufgelistet werden soll

|===


== Anfragetext

Ersetzt die gesamte gespeicherte Ressource durch den bereitgestellten JSON-Anfragetext, wobei Schlüsselwerte erhalten bleiben, die vom Benutzer nicht geändert werden können.

*Nebenwirkungen*

* Die Angabe einer Konfigurationsversion führt dazu, dass speicher-backend-spezifische Konfigurationsänderungen angewendet werden, was auch die Erstinstallation eines Speicher-Backends umfassen kann.
* Die Angabe einer Konfigurationsversion kann dazu führen, dass storageClass Ressourcen hinzugefügt, geändert oder entfernt werden.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 
Medientyp der Ressource. Definierte Werte sind:

* "application/astra-storageBackend"




| Version | Zeichenkette | Wahr  a| 
Version der Ressource. Definierte Werte sind:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | Zeichenkette | Falsch  a| 
Weltweit eindeutiger Bezeichner der Ressource. Definierte Werte sind:

* Entspricht dem UUIDv4-Schema




| backendName | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem benutzerdefinierten Namen für das Storage-Backend. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| backendType | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Typ des dargestellten Speichersystems angibt. Folgende Werte sind definiert:

* "ontap" – Das Speicher-Backend stellt ein NetApp ONTAP System dar.
* enum: ["ontap"]
* Beispiel: ONTAP




| backendVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die Version des verwendeten Storage-Backends angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| backendCredentialsName | Zeichenkette | Falsch  a| 
JSON-Zeichenfolge mit einem Wert, der den Namen einer oder mehrerer für das Speicher-Backend verwendeter Anmeldeinformationsressourcen angibt. Ermöglicht die Rotation von Anmeldeinformationen, wenn mehrere Anmeldeinformationsobjekte denselben Namen haben. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 63




| configVersion | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der die vom Speichersystem zu verwendende aktive Konfiguration angibt. Folgende Werte sind definiert:

* Mindestlänge: 1
* Maximale Länge: 63




| Zustand | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Betriebszustand des Storage-Backends angibt. Definierte Werte sind:

* „Erkannt“ – Das Speicher-Backend wurde von einem verwalteten Cluster erkannt.
* "läuft" – Das Storage-Backend läuft normal
* "unbekannt" – Der Status des Storage-Backends kann nicht ermittelt werden
* „failed“ – Das Storage-Backend befindet sich in einem nicht verfügbaren Zustand




| stateDesired | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den gewünschten Betriebszustand des Storage-Backends angibt. Definierte Werte sind:

* "läuft" - Das Storage-Backend befindet sich im normalen Betriebszustand




| stateUnready | Array[string] | Falsch  a| 
JSON-Array von JSON-Strings, die jeweils einen Grund dafür angeben, warum ein Storage-Backend nicht in den Status „running“ wechseln kann, warum es in den Status „failed“ oder „unknown“ gewechselt ist und/oder warum ein Wechsel in den Status „failed“ droht. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| managedState | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Verwaltungsstatus des Storage-Backends angibt. Definierte Werte sind:

* „pending“ – Das Storage-Backend ist zur Erkennung oder Hinzufügung geplant
* „unmanaged“ – Das Storage-Backend befindet sich im Status „discovered“, wird nicht verwaltet und ist für die Verwaltung geeignet
* „managed“ – Das Storage-Backend befindet sich im Status „running“ oder „unknown“ und wird verwaltet.




| managedStateUnready | Array[string] | Falsch  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum das Storage-Backend nicht verwaltet werden kann. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| healthState | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Integritätsstatus des Speichersystems angibt. Folgende Werte sind definiert:

* „unbestimmt“ – Der Zustand der Ressource kann nicht bestimmt werden (z. B. aufgrund fehlender Verbindung)
* „normal“ – Die Ressource weist keine bekannten Probleme auf und kann Dienste gemäß der Schnittstellenspezifikation bereitstellen.
* "Warnung" – Die Ressource weist bekannte Probleme auf, die sie jedoch nicht daran hindern, Dienste gemäß der Schnittstellenspezifikation bereitzustellen.
* "kritisch" – Die Ressource weist bekannte Probleme auf, die sie daran hindern, Dienste gemäß der Schnittstellenspezifikation bereitzustellen.




| healthStateUnready | Array[string] | Falsch  a| 
JSON-Array von JSON-Strings, die jeweils einen Grund dafür angeben, warum sich ein Storage-Backend nicht in einem normalen Gesundheitszustand befindet. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| protectionState | Zeichenkette | Falsch  a| 
JSON-Zeichenkette mit einem Wert, der den Schutzstatus des Storage-Backends angibt. „unknown“ für ONTAP. Definierte Werte sind:

* „geschützt“ – Das Storage-Backend verfügt über eine Datensicherungsstrategie und entspricht dieser Strategie.
* „teilweise“ – Das Storage-Backend hat eine Datensicherungsstrategie definiert, entspricht dieser jedoch nicht.
* „none“ – Das Storage-Backend ist nicht geschützt
* "unbekannt" – Die Einhaltung der Datensicherungsstrategie des Storage-Backends kann nicht ermittelt werden
* enum: ["geschützt", "teilweise", "keine", "unbekannt"]
* Beispiel: geschützt




| protectionStateUnready | Array[string] | Falsch  a| 
JSON-Array von JSON-Zeichenketten, die jeweils einen Grund dafür angeben, warum eine Datensicherungsstrategie nicht den Vorgaben entspricht. Definierte Werte sind:

* Mindestlänge: 1
* Maximale Länge: 127




| ONTAP | link:#ontap["ONTAP"] | Falsch  a| 
JSON-Objekt mit spezifischen Informationen zu ONTAP Clustern.

* additionalProperties: false




| Metadaten | link:#type_astra_metadata_update["type_astra_metadata_update"] | Falsch  a| 
Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


|===
.Beispielanfrage
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-storageBackend",
  "version": "1.3",
  "backendName": "st1-46"
}
----
====


== Antwort

[source]
----
Status: 204, Indicates if the storageBackend resource was updated.
----


== Antwort

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Antwort

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Antwort

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 



| invalidFields | Array[link:#invalidFields["invalidFields"]] | Falsch  a| 
Liste ungültiger Anfragetextfelder

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Antwort

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispielantwort
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Fehler

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Typ | Zeichenkette | Wahr  a| 



| Titel | Zeichenkette | Wahr  a| 



| Detail | Zeichenkette | Wahr  a| 



| Status | Zeichenkette | Wahr  a| 



| Korrelations-ID | Zeichenkette | Falsch  a| 

|===
.Beispiel-Fehlermeldung
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definitionen

.Siehe Definitionen
[%collapsible]
====
[role="api-collapsible-fifth-title"]
ONTAP

JSON-Objekt mit spezifischen Informationen zu ONTAP Clustern.

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| backendManagementIP | Zeichenkette | Falsch  a| 
JSON-Zeichenkette, die die IP-Adresse enthält, die zur Verbindung mit diesem ONTAP Cluster verwendet wird.



| Management-IPs | Array[string] | Falsch  a| 
Ein JSON-Array mit JSON-Strings, das die Liste aller möglichen Management-IPs enthält, die zur Verbindung mit diesem ONTAP Cluster verwendet werden. Dies wird verwendet, um Backends, die über Trident erkannt wurden, mit Speicher-Backends in Astra zu korrelieren.

* uniqueItems: 1


|===
[role="api-collapsible-fifth-title"]
Typ_Astra_Label

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 



| Wert | Zeichenkette | Wahr  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_update

Client- und dienstspezifische Metadaten, die der Ressource zugeordnet sind. Definierte Werte sind:

* Entspricht dem Astra-Metadatenschema. Wird beim Erstellen kein Label angegeben, wird ein Metadatenobjekt ohne Labels erstellt. Wird beim Aktualisieren kein Label angegeben, bleiben die Labels, creationTimestamp und createdBy, des Metadatenobjekts unverändert erhalten.


[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Etiketten | Array[link:#type_astra_label["Typ_Astra_Label"]] | Falsch  a| 



| CreationZeitstempel | Zeichenkette | Falsch  a| 



| Änderungszeitstempel | Zeichenkette | Falsch  a| 



| Erstellt von | Zeichenkette | Falsch  a| 



| modifiedBy | Zeichenkette | Falsch  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Abfrageparameters



| Grund | Zeichenkette | Wahr  a| 
Grund, warum der Abfrageparameter ungültig ist

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Name | Typ | Erforderlich | Beschreibung 


| Name | Zeichenkette | Wahr  a| 
Name des ungültigen Anfragetextfelds



| Grund | Zeichenkette | Wahr  a| 
Grund, warum das Anfragekörperfeld ungültig ist

|===
====