---
sidebar: sidebar 
permalink: workflows/wf_clone_app_snapshot.html 
keywords:  
summary: Sie können eine neue Applikation erstellen, indem Sie sie aus einem Snapshot klonen. 
---
= Eine Anwendung aus einem Snapshot klonen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine neue Applikation erstellen, indem Sie sie aus einem Snapshot klonen.



=== Bevor Sie beginnen

Beachten Sie Folgendes zu diesem Workflow:

* Ein App-Snapshot wird verwendet
* Der Klonvorgang wird im selben Cluster durchgeführt



NOTE: Zum Klonen einer App auf einem anderen Cluster müssen Sie den aktualisieren `clusterId` Parameter in den JSON-Input, wie es für Ihre Umgebung geeignet ist.



=== 1. Wählen Sie die zu klonenden App aus

Führen Sie den Workflow aus link:wf_list_man_apps.html["Listen Sie die Apps auf"] Und wählen Sie die Anwendung aus, die Sie klonen möchten. Für DEN REST-Aufruf, der zum Klonen der App verwendet wird, sind mehrere Ressourcenwerte erforderlich.



=== 2. Wählen Sie den zu verwendenden Snapshot aus

Führen Sie den Workflow aus link:wf_list_snapshots.html["Listen Sie die Snapshots auf"] Und wählen Sie den gewünschten Snapshot aus.



=== 3. Die App klonen

Führen Sie den folgenden REST-API-Aufruf aus.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| POST | /Accounts/{Account_id}/k8s/v2/Apps 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| JSON | Text | Ja. | Stellt die Parameter für die geklonte App bereit. Siehe das folgende Beispiel. 
|===


===== JSON-Eingabebeispiel

[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "name": "mysql-clone2",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "mysql",
  "snapshotID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----


===== Curl Beispiel: Klonen einer App aus einem Snapshot

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps' --header 'Content-Type: application/astra-app+json' --header '*/*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----