---
sidebar: sidebar 
permalink: workflows/wf_delete_failed_app.html 
keywords:  
summary: Sie können eine verwaltete Anwendung möglicherweise nicht entfernen, wenn eine Sicherung oder ein Snapshot in einem fehlgeschlagenen Zustand vorhanden ist. In diesem Fall können Sie die App manuell entfernen. 
---
= Löschen einer fehlgeschlagenen Anwendung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine verwaltete Anwendung möglicherweise nicht entfernen, wenn eine Sicherung oder ein Snapshot in einem fehlgeschlagenen Zustand vorhanden ist. In diesem Fall können Sie die App mithilfe des unten beschriebenen Workflows manuell entfernen.



=== 1. Wählen Sie die zu löschende App

Führen Sie den Workflow aus link:wf_list_man_apps.html["Listen Sie die Apps auf"] Und wählen Sie die Anwendung aus, die Sie entfernen möchten.



=== 2. Listen Sie die bestehenden Backups für die App auf

Führen Sie den Workflow aus link:wf_list_backups.html["Listen Sie die Backups auf"].



=== 3. Löschen Sie alle Backups

Löschen Sie alle App-Backups durch Ausführen des Workflows link:wf_delete_backup.html["Löschen Sie ein Backup"] Für jedes Backup in der Liste.



=== 4. Listen Sie die vorhandenen Snapshots für die App auf

Führen Sie den Workflow aus link:wf_list_snapshots.html["Listen Sie die Snapshots auf"].



=== 5. Löschen Sie alle Snapshots

Führen Sie den Workflow aus link:wf_delete_snapshot.html["Löschen Sie einen Snapshot"] Von jedem Snapshot in der Liste.



=== 6. Entfernen Sie die Anwendung

Führen Sie den Workflow aus link:wf_unmanage_app.html["Verwaltung einer Anwendung aufheben"] Um die Anwendung zu entfernen.
