---
sidebar: sidebar 
permalink: workflows/wf_delete_backup.html 
keywords:  
summary: Sie können ein Backup einer Anwendung löschen. 
---
= Löschen Sie ein Backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können ein Backup einer Anwendung löschen.



=== Bevor Sie beginnen

Sie müssen Folgendes haben:

* ID der Applikation, für die das Backup zuständig ist. Bei Bedarf können Sie den Workflow verwenden link:wf_list_man_apps.html["Listen Sie die Apps auf"] Zum Auffinden der Anwendung.
* ID des zu löschenden Backups. Bei Bedarf können Sie den Workflow verwenden link:wf_list_backups.html["Listen Sie die Backups auf"] Um den Snapshot zu finden.




=== 1. Löschen Sie die Sicherung

Führen Sie den folgenden REST-API-Aufruf aus.


NOTE: Sie können das Löschen einer fehlgeschlagenen Sicherung wie unten beschrieben mit der optionalen Anforderungs-Kopfzeile erzwingen.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| Löschen | /Accounts/{Account_id}/k8s/v1/Apps/{App_id}/appBackups/{appBackup_id} 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| App-id | Pfad | Ja. | Gibt die verwaltete Anwendung an, die das Backup besitzt. 


| Backup-id | Pfad | Ja. | Identifiziert das zu löschende Backup. 


| Löschen erzwingen | Kopfzeile | Nein | Wird verwendet, um das Löschen eines fehlgeschlagenen Backups zu erzwingen. 
|===


===== Curl Beispiel: Löschen Sie ein einzelnes Backup für die App

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl Beispiel: Löschen Sie eine einzelne Sicherung für die App mit der Force-Option

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --header 'Force-Delete: true'
----