---
sidebar: sidebar 
permalink: workflows/wf_get_man_app.html 
keywords:  
summary: Sie können alle Ressourcenvariablen abrufen, die eine einzelne Anwendung beschreiben. 
---
= Holen Sie sich eine App
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können alle Ressourcenvariablen abrufen, die eine einzelne Anwendung beschreiben.



=== Bevor Sie beginnen

Sie müssen die ID der App haben, die Sie abrufen möchten. Bei Bedarf können Sie den Workflow verwenden link:wf_list_man_apps.html["Listen Sie die Apps auf"] Zum Auffinden der Anwendung.



=== 1. Holen Sie sich die Anwendung

Führen Sie den folgenden REST-API-Aufruf aus.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| GET | /Accounts/{Account_id}/k8s/v2/Apps/{App_id} 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| App-id | Pfad | Ja. | ID-Wert der abzurufenden Anwendung. 
|===


===== Curl Beispiel: Alle Daten für die Anwendung zurückgeben

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps/<APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----