---
sidebar: sidebar 
permalink: workflows/wf_restore_app_backup.html 
keywords:  
summary: Sie können eine Applikation wiederherstellen, indem Sie eine neue Applikation aus einem Backup erstellen. 
---
= Wiederherstellung einer Anwendung aus einem Backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine Applikation wiederherstellen, indem Sie eine neue Applikation aus einem Backup erstellen.



=== 1. Wählen Sie die Anwendung, die wiederhergestellt werden soll

Führen Sie den Workflow aus link:wf_list_man_apps.html["Listen Sie die Apps auf"] Und wählen Sie die Anwendung aus, die Sie klonen möchten. Für DEN REST-Aufruf, der zur Wiederherstellung der App verwendet wird, sind mehrere Ressourcenwerte erforderlich.



=== 2. Wählen Sie das zu verwendende Backup aus

Führen Sie den Workflow aus link:wf_list_backups.html["Listen Sie die Backups auf"] Und wählen Sie das gewünschte Backup aus.



=== 3. Stellen Sie die App wieder her

Führen Sie den folgenden REST-API-Aufruf aus. Sie müssen die ID für ein Backup (wie unten gezeigt) oder einen Snapshot angeben.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| PUT | /Accounts/{Account_id}/k8s/v2/Apps/{App_id} 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| JSON | Text | Ja. | Stellt die Parameter für die geklonte App bereit. Siehe das folgende Beispiel. 
|===


===== JSON-Eingabebeispiel

[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----


===== Curl Beispiel: Wiederherstellen einer vorhandenen Applikation aus einem Backup

[source, curl]
----
curl --location -i --request PUT 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps/<APP_ID>' --header 'Content-Type: application/astra-app+json' --header '*/*' --header 'ForceUpdate: true' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----