---
sidebar: sidebar 
permalink: workflows/wf_unmanage_app.html 
keywords:  
summary: Sie können eine verwaltete Anwendung entfernen, wenn sie nicht mehr benötigt wird. Durch Entfernen einer verwalteten Anwendung werden auch die zugeordneten Zeitpläne gelöscht. 
---
= Verwaltung einer Anwendung aufheben
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine verwaltete Anwendung entfernen, wenn sie nicht mehr benötigt wird. Durch Entfernen einer verwalteten Anwendung werden auch die zugeordneten Zeitpläne gelöscht.



=== Bevor Sie beginnen

Sie müssen über die ID der App verfügen, die Sie verwalten möchten. Bei Bedarf können Sie den Workflow verwenden link:wf_list_man_apps.html["Listen Sie die Apps auf"] Zum Auffinden der Anwendung.

Backups und Snapshots der Applikation werden nicht automatisch entfernt, wenn sie gelöscht wird. Wenn Sie die Backups und Snapshots nicht mehr benötigen, sollten Sie sie löschen, bevor Sie die Anwendung entfernen.



=== 1. Die App wurde nicht verwaltet

Führen Sie den folgenden REST-API-Aufruf durch, um die App zu entfernen.

[cols="25,75"]
|===
| HTTP-Methode | Pfad 


| Löschen | /Accounts/{Account_id}/k8s/v2/Apps/{App_id} 
|===


===== Zusätzliche Eingabeparameter

Zusätzlich zu den Parametern, die bei allen REST-API-Aufrufen üblich sind, werden die folgenden Parameter auch in den Curl-Beispielen für diesen Schritt verwendet.

[cols="25,10,10,55"]
|===
| Parameter | Typ | Erforderlich | Beschreibung 


| App-id | Pfad | Ja. | Identifiziert die zu entfernende Anwendung. 
|===


===== Curl Beispiel: Eine verwaltete App entfernen

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps/<APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----