---
sidebar: sidebar 
permalink: get-started/get_api_token.html 
keywords: token, obtain token 
summary: Sie müssen ein Astra API Token erhalten, um die Astra Control REST API zu verwenden. 
---
= Holen Sie sich ein API-Token
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie müssen ein Astra API Token erhalten, um die Astra Control REST API zu verwenden.



== Überblick

Ein API-Token identifiziert den Anrufer an Astra und muss bei jedem REST-API-Aufruf enthalten sein.

* Sie müssen über die Astra Web-Benutzeroberfläche ein API-Token generieren.
* Das Verfahren zum Generieren eines Tokens ist für beide Astra-Implementierungsmodelle gleich. Nur die URL, die für den Zugriff auf Astra verwendet wird, ist anders.
* Die mit dem Token übermittelte Benutzeridentität und die zugehörigen Berechtigungen werden vom Benutzer bestimmt, der das Token erstellt hat.
* Das Token muss in das enthalten sein `Authorization` HTTP-Anfragekopf.
* Ein Token läuft nie ab, nachdem es erstellt wurde.
* Sie können ein Token über die Astra Web-Benutzeroberfläche widerrufen.


.Verwandte Informationen
* link:../additional/revoke_token.html["Ein API-Token widerrufen"]




== Erstellen Sie ein Astra API-Token

In den folgenden Schritten wird beschrieben, wie ein Astra API Token erstellt wird.

.Bevor Sie beginnen
Sie benötigen die Zugangsdaten für ein Astra-Konto.

.Über diese Aufgabe
Diese Aufgabe erzeugt ein API-Token in der Astra-Webschnittstelle. Sie sollten auch die Account-ID abrufen, die auch bei API-Aufrufen benötigt wird.

.Schritte
. Melden Sie sich mit Ihren Account-Anmeldedaten für Astra wie folgt an:
+
** Astra Control Service: link:https://astra.netapp.io["https://astra.netapp.io"^]
** Astra Control Center: Verwenden Sie die bei der Installation festgelegte URL für Ihre lokale Umgebung


. Klicken Sie auf das Figurensymbol oben rechts auf der Seite und wählen Sie *API Access*.
. Klicken Sie auf der Seite auf *API-Token generieren* und klicken Sie dann im Popup-Fenster auf *API-Token generieren*.
. Klicken Sie auf das Symbol, um die Token-Zeichenfolge in die Zwischenablage zu kopieren und im Editor zu speichern.
. Kopieren Sie die Konto-id, die auf derselben Seite verfügbar ist, und speichern Sie sie.


.Nachdem Sie fertig sind
Wenn Sie über Curl oder eine Programmiersprache auf die Astra Control REST-API zugreifen, müssen Sie das API-Trägertoken in das HTTP einschließen `Authorization` Kopfzeile der Anfrage.
