---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: Sie können auf die Details der Astra Control REST-API-Aufrufe zugreifen, einschließlich HTTP-Methoden, Eingabeparameter und Antworten. Diese vollständige Referenz ist hilfreich, wenn Automatisierungsapplikationen mithilfe der REST API entwickelt werden. 
---
= Online-API-Referenz
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können auf die Details der Astra Control REST-API-Aufrufe zugreifen, einschließlich HTTP-Methoden, Eingabeparameter und Antworten. Diese vollständige Referenz ist hilfreich, wenn Automatisierungsapplikationen mithilfe der REST API entwickelt werden.


NOTE: Die REST-API-Referenzdokumentation wird derzeit mit Astra Control bereitgestellt und ist online verfügbar.

.Bevor Sie beginnen
Sie benötigen ein Konto für Astra Control Center oder Astra Control Service.

.Schritte
. Melden Sie sich mit Ihren Anmeldedaten im Astra an.
+
Rufen Sie die folgende Website für den Astra Control Service auf: link:https://astra.netapp.io["https://astra.netapp.io"^]

. Klicken Sie auf das Figurensymbol oben rechts auf der Seite und wählen Sie *API Access*.
. Klicken Sie oben auf der Seite auf die URL, die unter *API Documentation* angezeigt wird.
. Geben Sie bei Aufforderung erneut Ihre Anmeldeinformationen für das Konto an.

