---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: Sie können auf die Details der Astra Control REST-API-Aufrufe zugreifen, einschließlich HTTP-Methoden, Eingabeparameter und Antworten. Diese vollständige Referenz ist hilfreich, wenn Automatisierungsapplikationen mithilfe der REST API entwickelt werden. 
---
= Zugriff auf die Referenzdokumentation zur Astra API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können auf die Details der Astra Control REST-API-Aufrufe zugreifen, einschließlich HTTP-Methoden, Eingabeparameter und Antworten. Diese vollständige Referenz ist hilfreich, wenn Automatisierungsapplikationen mithilfe der REST API entwickelt werden.

.Bevor Sie beginnen
Sie benötigen die Zugangsdaten, um sich für Ihre Implementierung in der Astra Web-Benutzeroberfläche anzumelden. Für Astra Control Service und Astra Control Center gilt die gleiche Vorgehensweise für den Zugriff auf die Referenzdokumentation. Nur die URL ist anders. Ein API-Token ist nicht erforderlich, um auf das Referenzdok zuzugreifen und es anzuzeigen.

.Schritte
. Melden Sie sich mit Ihren Account-Anmeldedaten für Astra wie folgt an:
+
** Astra Control Service: link:https://astra.netapp.io["https://astra.netapp.io"^]
** Astra Control Center: Verwenden Sie die bei der Installation festgelegte URL für Ihre lokale Umgebung


. Klicken Sie auf das Figurensymbol oben rechts auf der Seite und wählen Sie *API Access*.
. Klicken Sie oben auf der Seite auf die URL, die unter *API Documentation* angezeigt wird.


.Ergebnis
Die Seite Swagger wird in einem neuen Fenster oder Tab geöffnet. Hinweis: Die URL enthält die Konto-ID für das Konto, bei dem Sie sich angemeldet haben.

.Was kommt als Nächstes?
Sie können optional einen API-Aufruf von der Seite Swagger ausführen. Siehe link:../get-started/online_api_call.html["Einen Astra-REST-API-Aufruf ausgeben"] Finden Sie weitere Informationen.
